// ── 店舗データ ─────────────────────────────────────────────────
// detail.html と script.js の両方から読み込む共通データファイル
const restaurants = [
  {
    id:          0,
    code:        "47213-IS-0001",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-16",
    name:      "酒楽場うまし家",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川1丁目28-18",
    hours:     "17:00〜翌1:00",
    closed:    "火曜日",
    note:      "創業40年超。石川社交街の老舗大衆居酒屋。県産無農薬野菜使用",
    note_en:   "Over 40 years in business. A long-established izakaya in Ishikawa's entertainment district. Uses locally grown organic vegetables.",
    sourceUrl: "https://umashiya.com/",
    sourceUrls: ["https://umashiya.com/", "https://www.ekiten.jp/shop_2457951/", "https://map.yahoo.co.jp/v3/place/X0m4ICbJzsI"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "sourceUrlを下層ページ（/about/）からトップページ（umashiya.com/）に修正（備考の内容自体はトップページで確認できるため、内容変更なし）" }
    ],
    warn:      false,
    lat:       26.430443,
    lng:       127.828701,
    // 詳細ページ用フィールド
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "https://umashiya.com/",
    detailText: "",
    photos:     []
  },
  {
    id:          1,
    code:        "47213-IS-0002",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-16",
    name:      "クリームソーダ",
    genre:     "バル（中華・和食・バー）",
    address:   "沖縄県うるま市石川白浜1-2-1 2F",
    hours:     "中華ランチ：月・木・金 11:30〜14:00\nBAR：年中無休 18:00〜\n中華ディナー：土・日 18:00〜21:00",
    closed:    "不定休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://balcreamsoda.com/",
    sourceUrls: ["https://balcreamsoda.com/", "https://okinawaly.com/living/post-1103/"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "備考「営業スタイルが複雑。訪問前に公式サイトで要確認」を削除。事実（曜日ごとに業態が異なること）自体はhours欄に記載済みで正確だったが、「複雑」「要確認」という評価・要約の言葉自体は出典に存在せず、AIが自分の言葉で書いていたため" }
    ],
    warn:      false,
    lat:       26.427302,
    lng:       127.827541,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "https://balcreamsoda.com/",
    detailText: "",
    photos:     []
  },
  {
    id:          2,
    code:        "47213-IS-0003",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-16",
    name:      "杏屋 石川店",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川白浜1-4-7",
    hours:     "18:00〜翌3:00（料理L.O. 翌1:45）",
    closed:    "不定休",
    note:      "深夜営業。個室あり。飲み放題コースあり",
    note_en:   "Late-night hours. Private rooms available. All-you-can-drink courses offered.",
    sourceUrl: "https://www.instagram.com/anzuya.ishikawa/",
    sourceUrls: ["https://www.instagram.com/anzuya.ishikawa/"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "sourceUrlを公式Instagramに変更（従来のホットペッパー・Yahoo!地図は複製・転載を禁止する規約があるため転記元から除外）。定休日「なし（年中無休）」を公式Instagramの記載「不定休」に修正" }
    ],
    warn:      false,
    lat:       26.428326,
    lng:       127.827701,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          3,
    code:        "47213-IS-0004",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-09",
    listedDate:  "2026-05-16",
    name:      "牛角 うるま石川店",
    genre:     "焼肉",
    address:   "沖縄県うるま市石川1-16-18",
    hours:     "16:00〜23:00",
    closed:    "年中無休",
    note:      "チェーン店（牛角グループ）",
    note_en:   "Chain restaurant (Gyukaku group).",
    sourceUrl: "https://map.reins.co.jp/gyukaku/detail/989653529",
    sourceUrls: ["https://map.reins.co.jp/gyukaku/detail/989653529"],
    revisionHistory: [
      { date: "2026-08-09", type: "ai", note: "sourceUrlsからぐるなび（r.gnavi.co.jp）を除去（利用規約に転載・複製禁止条項を確認したため）。sourceUrl（map.reins.co.jp）は牛角の運営会社「株式会社レインズインターナショナル」自身の公式サイトと判明し、安全な情報源として引き続き採用。営業時間・定休日・備考は同公式サイトの記載と一致することを確認" }
    ],
    warn:      false,
    lat:       26.431203,
    lng:       127.825063,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          4,
    code:        "47213-IS-0005",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-09",
    listedDate:  "2026-05-16",
    name:      "Capful（キャプフル）",
    genre:     "カフェ",
    address:   "沖縄県うるま市石川曙1丁目6-1",
    hours:     "8:00〜15:30（L.O.15:00）",
    closed:    "水曜日",
    note:      "海が見えるテラス席。朝食営業あり",
    note_en:   "Terrace seating with ocean view. Breakfast available.",
    sourceUrl: "https://www.instagram.com/okinawa_capful/",
    sourceUrls: ["https://www.instagram.com/okinawa_capful/", "https://okinawatravel.jp/capful"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "備考「元外国人住宅を改装。」を削除（登録している出典2件のいずれにも該当する記載がなく確認できなかったため）" },
      { date: "2026-08-09", type: "ai", note: "営業時間「7:30〜15:30（月〜木）／7:30〜21:00（金・土・日）」を「8:00〜15:30（L.O.15:00）」に修正（公式Instagramのプロフィール記載「Mon-Sun 8:00am-3:30pm（L.O3:00）」と一致させた。金土日の夜間延長営業〈〜21:00〉は公式Instagram・第三者サイトのいずれにも裏付けがなく削除）。定休日「水曜日」は公式Instagramの記載と一致確認" }
    ],
    warn:      false,
    lat:       26.420088,
    lng:       127.828450,
    twitter:    "",
    instagram:  "https://www.instagram.com/okinawa_capful/",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          5,
    code:        "47213-IS-0006",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-16",
    name:      "HINA CAFE（ヒナカフェ）",
    genre:     "カフェ・イタリアン",
    address:   "沖縄県うるま市石川白浜1-1-1 2F",
    hours:     "月〜金 11:30〜15:00（L.O.14:00）\n土・日 11:30〜15:30（L.O.15:00）",
    closed:    "水曜日",
    note:      "2023年6月オープン。本格イタリアン",
    note_en:   "Opened June 2023. Authentic Italian cuisine.",
    sourceUrl: "https://hinacafe-ishikawa-urumacity.jimdofree.com/",
    sourceUrls: ["https://hinacafe-ishikawa-urumacity.jimdofree.com/"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "sourceUrlを公式サイトに変更（従来のひとさら・食べログは複製・転載を禁止する規約があるため転記元から除外）。営業時間・定休日を公式サイトの記載に修正（従来のディナー営業〈金〜日16:00〜22:00〉・定休日「月〜水」の記載は公式サイトで確認できず、ランチ営業のみ・水曜定休が正しい内容だった）" }
    ],
    warn:      false,
    lat:       26.427231,
    lng:       127.827883,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          6,
    code:        "47213-IS-0007",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-16",
    name:      "GENCO（ジェンコ）",
    genre:     "カフェ・バー（ハワイ料理）",
    address:   "沖縄県うるま市石川伊波1515-32",
    hours:     "11:11〜24:00（L.O.22:00）",
    closed:    "火曜日",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.instagram.com/okinawa_cafebar_genco/",
    sourceUrls: ["https://www.instagram.com/okinawa_cafebar_genco/", "https://ryukyushimpo.jp/style/gourmet/entry-2823371.html"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「訪問前に電話確認を推奨（098-988-5863）」を削除（読者への行動の呼びかけ・変更されうる電話番号の転記は行わない方針としたため）" },
      { date: "2026-08-08", type: "ai", note: "sourceUrlを公式Instagramに変更（従来の食べログは複製・転載を禁止する規約があるため転記元から除外）。営業時間を公式Instagramの記載「11:11〜24:00（L.O.22:00）」に修正（従来は分割2部制だったが通し営業が正しい）。備考「食べログに営業状況『未確認』の記載あり」を削除（食べログを出典として扱わない方針としたため）" }
    ],
    warn:      true,
    warnReason: "continuity",
    lat:       26.433345,
    lng:       127.808541,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          7,
    code:        "47213-IS-0008",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-16",
    name:      "Cafe Ajyute（カフェアジュテ）",
    genre:     "カフェ・パン",
    address:   "沖縄県うるま市石川2140-5",
    hours:     "月〜金 10:00〜16:00（L.O. 15:30）\n※パン売り切れ次第終了",
    closed:    "土・日・祝日",
    note:      "就労継続支援施設が運営。焼きたてパン食べ放題（1時間 1,000円・ドリンク込み）",
    note_en:   "Run by a welfare support facility. All-you-can-eat freshly baked bread (1 hr / ¥1,000 incl. drink).",
    sourceUrl: "https://www.instagram.com/cafeajyute/",
    sourceUrls: ["https://www.instagram.com/cafeajyute/", "https://snabi.jp/facility/18262"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "公式サイト（ajyute.com）が閉鎖済みのため、sourceUrl・websiteをInstagram公式アカウントに変更。備考の料金（1時間1,000円）は最新の複数情報源と一致することを確認、内容自体の変更なし" }
    ],
    warn:      false,
    lat:       26.416168,
    lng:       127.832946,
    twitter:    "",
    instagram:  "https://www.instagram.com/cafeajyute/",
    youtube:    "",
    website:    "https://www.instagram.com/cafeajyute/",
    detailText: "",
    photos:     []
  },
  {
    id:          8,
    code:        "47213-IS-0009",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-16",
    name:      "喜食てんてん",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川山城1706-6",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47013479/",
    sourceUrls: ["https://tabelog.com/okinawa/A4703/A470302/47013479/", "https://www.ekiten.jp/shop_71083176/"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "備考「（もも肉1.5枚分のボリューム）」を削除（出典2件のいずれにも該当する記載がなかったため）" },
      { date: "2026-08-08", type: "ai", note: "食べログ・エキテンは複製・転載を禁止する規約があるため転記元から除外することとし、両サイトのみに依存していた営業時間・定休日・備考を「要確認」／空欄に変更。代替の公式サイト・公式SNSは調査したが見つからなかった。リンク自体は発見の手がかりとして残置" }
    ],
    warn:      true,
    lat:       26.412381,
    lng:       127.820619,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          9,
    code:        "47213-IS-0010",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-16",
    name:      "居酒屋パラダイス",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川2丁目39-15",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47007823/",
    sourceUrls: ["https://tabelog.com/okinawa/A4703/A470302/47007823/", "https://www.ekiten.jp/shop_7136480/", "https://hitosara.com/0031479619/"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "備考「・カツチャーハン」「地元客に人気」を削除（登録している出典3件のいずれにも該当する記載がなかったため）" },
      { date: "2026-08-08", type: "ai", note: "食べログ・エキテン・ひとさらは複製・転載を禁止する規約があるため転記元から除外することとし、これらのみに依存していた営業時間・定休日・備考を「要確認」／空欄に変更。代替の公式サイト・公式SNSは調査したが見つからなかった。リンク自体は発見の手がかりとして残置" }
    ],
    warn:      true,
    lat:       26.427576,
    lng:       127.821275,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },

  // ── 追加10店舗（2026-05-08） ─────────────────────────────────────
  {
    id:          10,
    code:        "47213-IS-0011",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-09",
    listedDate:  "2026-05-16",
    name:      "まるみつ食堂",
    genre:     "食事処",
    address:   "沖縄県うるま市石川東山1丁目22-11",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://ryukyu-entertainment.com/marumitu/",
    sourceUrls: ["https://ryukyu-entertainment.com/marumitu/"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "備考「1949年創業」「てびちそば・三枚肉そばが名物」「昭和の食堂」を削除し、出典の実際の記載「創業60年以上」「地元民から愛される」に基づく表現に修正。リンク切れの情報源（retty.me、404）を削除" },
      { date: "2026-08-09", type: "ai", note: "唯一の情報源（ryukyu-entertainment.com）が、まるみつ食堂とは無関係な第三者の観光・エンタメ会社サイトと判明（運営会社ではない）。明文の転載禁止規約は見つからなかったが、店舗公式でも公的機関でもないため、営業時間・定休日・備考を「要確認」／空欄に変更。リンク自体は発見の手がかりとして残置" }
    ],
    warn:      true,
    lat:       26.4347222,
    lng:       127.8380556,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          11,
    code:        "47213-IS-0012",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-16",
    name:      "和カフェ Agariyama（アガリヤマ）",
    genre:     "カフェ・八重山そば",
    address:   "沖縄県うるま市石川東山1-8-3",
    hours:     "水〜金 10:00〜15:00 / 17:00〜22:00\n土・日は要確認",
    closed:    "要確認",
    note:      "2024年5月オープン。石垣島出身オーナーのログハウス風隠れ家カフェ。八重山そばも提供",
    note_en:   "Opened May 2024. Hidden log-cabin café by an owner from Ishigaki Island. Also serves Yaeyama soba.",
    sourceUrl: "https://www.instagram.com/wa_cafe_agariyama/",
    sourceUrls: ["https://www.instagram.com/wa_cafe_agariyama/", "https://omalblog.com/2024/12/08/uruma-gariyama/"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "sourceUrlを公式Instagramに変更（従来のYahoo!地図は複製・転載を禁止する規約があるため転記元から除外）。公式Instagramで平日（水〜金）の営業時間・住所は確認できたが、土日の詳細時間・定休日（月・火）は確認できなかったため「要確認」に変更" }
    ],
    warn:      true,
    lat:       26.4373232,
    lng:       127.8354213,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          12,
    code:        "47213-IS-0013",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-16",
    name:      "大衆酒場 照らす家 石川店",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川白浜1丁目3-5",
    hours:     "日〜木 17:00〜0:00\n金・土・祝前日 17:00〜翌3:00",
    closed:    "要確認",
    note:      "飲み放題プランあり",
    note_en:   "All-you-can-drink plans available.",
    sourceUrl: "https://www.instagram.com/ishikawaterasuya/",
    sourceUrls: ["https://www.instagram.com/ishikawaterasuya/"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "備考「セルフスタイルの」「（990円〜）」「が人気」を削除（出典2件のいずれにも確認できず、口コミでは980円という近いが不一致な金額のみ見つかったため）" },
      { date: "2026-08-08", type: "ai", note: "備考「訪問前に営業時間を確認推奨」を削除（読者への行動の呼びかけは書かない方針としたため）" },
      { date: "2026-08-08", type: "ai", note: "sourceUrlを公式Instagramに変更（従来の食べログ・ひとさらは複製・転載を禁止する規約があるため転記元から除外）。営業時間を公式Instagramの記載に修正（従来「17:00〜翌3:00」は金・土・祝前日のみで、日〜木は0:00閉店が正しい）" }
    ],
    warn:      true,
    lat:       26.427654,
    lng:       127.8269779,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          13,
    code:        "47213-IS-0014",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-16",
    name:      "榮料理店（さかえりょうりてん）",
    genre:     "食事処",
    address:   "沖縄県うるま市石川伊波1553-463",
    hours:     "18:00〜21:30",
    closed:    "日曜日・不定休",
    note:      "予約必須のコース料理専門店（2種から選択）",
    note_en:   "Reservation required. Course-only menu (choice of 2 courses).",
    sourceUrl: "http://niraicuisine.com/gaiyou.html",
    sourceUrls: ["http://niraicuisine.com/gaiyou.html", "https://www.instagram.com/sakae.niraicuisine/"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "公式サイト（niraicuisine.com）がSSL証明書エラーでアクセス不能、副情報源も404のため、sourceUrl・websiteを食べログに変更。備考「地元・米軍関係者にも人気の名店」を削除（複数の出典・口コミのいずれにも米軍関係者への言及がなく根拠不明のため）。「コース料理のみ」は食べログで確認できたため維持" },
      { date: "2026-08-08", type: "ai", note: "公式サイト（niraicuisine.com）に再度アクセスしたところ復旧しており、営業時間・定休日とも会社概要ページの記載と完全一致することを確認。sourceUrl・websiteを公式サイトに変更（従来の食べログ・ホットペッパーは複製・転載を禁止する規約があるため転記元から除外）" }
    ],
    warn:      false,
    lat:       26.4341514,
    lng:       127.8112099,
    twitter:    "",
    instagram:  "https://www.instagram.com/sakae.niraicuisine/",
    youtube:    "",
    website:    "http://niraicuisine.com/",
    detailText: "",
    photos:     []
  },
  {
    id:          14,
    code:        "47213-IS-0015",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-16",
    name:      "パーラー K's Pit（ケーズピット）",
    genre:     "食事処",
    address:   "沖縄県うるま市石川曙1丁目2-17",
    hours:     "要確認",
    closed:    "不定休",
    note:      "2022年オープン。本格アメリカンバーガーやスイーツを提供。屋上にオーシャンビューテラス席あり",
    note_en:   "Opened 2022. Serves authentic American-style burgers and sweets. Rooftop ocean-view terrace available.",
    sourceUrl: "http://kspit.jp/",
    sourceUrls: ["http://kspit.jp/", "https://www.instagram.com/kspit_parlor_okinawa/", "https://www.otv.co.jp/okitive/article/23464/"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「本格アメリカンバーガー専門店」を「本格アメリカンバーガーやスイーツを提供」に修正（出典の実際の記載は「ハンバーガーやスイーツを提供しているお店」で、専門店と言い切るのはやや誇張だったため）" },
      { date: "2026-08-08", type: "ai", note: "sourceUrlを公式サイト・公式Instagramに変更（従来のYahoo!地図・食べログは複製・転載を禁止する規約があるため転記元から除外）。営業時間は公式サイト・報道記事（OTV）・公式Instagramの3者で開店/閉店時刻が食い違っており（10時/11時、18時/20時）一意に確定できないため「要確認」に変更" }
    ],
    warn:      true,
    lat:       26.421304,
    lng:       127.826424,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          15,
    code:        "47213-IS-0016",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-16",
    name:      "たらの芽",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川白浜2丁目3-2",
    hours:     "ランチ 12:00〜14:00\n居酒屋 17:30〜24:00",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.instagram.com/taranome0319/",
    sourceUrls: ["https://www.instagram.com/taranome0319/", "https://okinawa-tabearuki.com/archives/666"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "備考「地元民に愛される老舗の和食居酒屋。刺身定食・天ぷらが名物」を削除（出典3件（食べログ・okinawa-tabearuki.com・Yahoo地図）のいずれにも該当する記載がなく、実態不明のため）" },
      { date: "2026-08-08", type: "ai", note: "sourceUrlを公式Instagramに変更（従来の食べログ・Yahoo!地図は複製・転載を禁止する規約があるため転記元から除外）。ランチ時間は公式Instagramで一致確認。夜の営業時間を公式Instagramの記載「17:30〜24:00」に修正（従来「翌1:00」の裏付けなし）。定休日「日曜日」は裏付けが取れず「要確認」に変更" }
    ],
    warn:      false,
    lat:       26.4272451,
    lng:       127.8270008,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          16,
    code:        "47213-IS-0017",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-16",
    name:      "石川 柿兵衛（かきべえ）",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川1丁目14-2",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.instagram.com/kakibei_ishikawaten/",
    sourceUrls: ["https://www.instagram.com/kakibei_ishikawaten/"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "ホットペッパー・Rettyは複製・転載を禁止する規約があるため転記元から除外することとし、これらのみに依存していた営業時間・定休日・備考を「要確認」／空欄に変更。sourceUrlは存在確認できた公式Instagramに変更したが、営業時間の記載はなく裏付けにはならない" }
    ],
    warn:      true,
    lat:       26.4298734,
    lng:       127.822802,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          17,
    code:        "47213-IS-0018",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-16",
    name:      "麺や KEIJIRO 石川店",
    genre:     "ラーメン",
    address:   "沖縄県うるま市石川1丁目28-19",
    hours:     "11:00〜16:00 / 18:00〜翌4:00",
    closed:    "不定休（月・金の昼営業なし）",
    note:      "石川店限定の骨汁（700円）が名物。深夜4時まで営業",
    note_en:   "Famous for the Ishikawa-branch-exclusive bone soup (¥700). Open until 4am.",
    sourceUrl: "https://www.otv.co.jp/okitive/article/95697/",
    sourceUrls: ["https://www.otv.co.jp/okitive/article/95697/", "https://www.instagram.com/keijiro.ishikawa/"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "備考「濃厚鶏白湯スープが特徴」を「骨汁（700円）が名物」に修正（出典に「濃厚鶏白湯スープ」の記載はなく、石川店限定と紹介されているのは実際には骨汁だったため）" },
      { date: "2026-08-08", type: "ai", note: "sourceUrlsから規約違反サイト（Retty・Yahoo!地図）を除去し、公式Instagramを追加。報道記事（OTV）は営業時間・定休日とも現行データと完全一致することを再確認済み" }
    ],
    warn:      false,
    lat:       26.4303538,
    lng:       127.8286398,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          18,
    code:        "47213-IS-0019",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-16",
    name:      "石川の駅",
    genre:     "食事処",
    address:   "沖縄県うるま市石川赤崎2丁目2-1",
    hours:     "要確認",
    closed:    "要確認",
    note:      "ホームセンタータバタ石川店内の食堂",
    note_en:   "Diner inside Tabata Home Center Ishikawa.",
    sourceUrl: "http://batabata.jp/shop/",
    sourceUrls: ["http://batabata.jp/shop/", "https://www.facebook.com/hc.tabata/"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "備考「ステーキ定食」を「ステーキサンド」に修正（出典に「ステーキ定食」の記載はなく、実際の名物は「ステーキサンド」だったため）" },
      { date: "2026-08-08", type: "ai", note: "食べログ・Yahoo!地図・Rettyは複製・転載を禁止する規約があるため転記元から除外。運営会社（ホームセンタータバタ）の公式サイト・公式Facebookでは店舗の実在は確認できたが「石川の駅」固有の営業時間・定休日の記載は見つからず「要確認」に変更。備考のメニュー詳細（ステーキサンド等）も裏付けが取れないため削除し、位置づけの記載のみ残した" }
    ],
    warn:      true,
    lat:       26.4342224,
    lng:       127.8353657,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          19,
    code:        "47213-IS-0020",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-16",
    name:      "酒処 金の蔵（きんのくら）",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川1丁目28-9",
    hours:     "ランチ 11:00〜15:00\n夜 18:00〜24:00",
    closed:    "月曜日・日曜日",
    note:      "同じ建物に姉妹店「キンクラバーガー」あり",
    note_en:   "Sister restaurant 'Kinkura Burger' is located in the same building.",
    sourceUrl: "https://r.goope.jp/kinnokura/",
    sourceUrls: ["https://r.goope.jp/kinnokura/", "https://r.goope.jp/kinnokura/about", "https://tabelog.com/okinawa/A4703/A470302/47026871/"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "sourceUrlをFacebook（内容確認不能）から公式サイトに変更（公式サイトのトップページに「金の蔵・Kinkura Burgerからのお知らせ」の記載があり、備考の内容を確認できたため）" }
    ],
    warn:      false,
    lat:       26.430094,
    lng:       127.828385,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "https://r.goope.jp/kinnokura/",
    detailText: "",
    photos:     []
  },

  // ── コンビニエンスストア ──────────────────────────────────────────
  {
    id:          20,
    code:        "47213-IS-0021",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-05-23",
    name:      "ローソン うるま石川店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川2-24-9",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.areamarker.com/lawson/info/212096?addresscode=47213&shopid=212096",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「ATM・コピー機あり」を削除（登録している出典のいずれにも設備情報の記載がなかったため）" },
      { date: "2026-08-11", type: "ai", note: "sourceUrlを本部の汎用トップページから、ローソン公式店舗検索（areamarker.com）の店舗固有ページに変更（住所・営業時間の記載が一致することを確認、ユーザーが実際のブラウザ画面で表示を確認）。sourceUrlsのマピオンは除去" }
    ],
    warn:      false,
    lat:       26.42517,
    lng:       127.82526,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },
  {
    id:          21,
    code:        "47213-IS-0022",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-05-23",
    name:      "ファミリーマート 石川一丁目店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川1-27-41",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://store.family.co.jp/points/72085",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「ATM・イートインスペースあり」を削除（登録している出典のいずれにも設備情報の記載がなかったため）" },
      { date: "2026-08-11", type: "ai", note: "sourceUrlを本部の汎用トップページから、この店舗固有の店舗検索ページ（store.family.co.jp/points/72085）に変更（住所の記載が一致することを確認）。石川白浜店での同様の指摘を受け、他のファミマ店舗も一括対応" }
    ],
    warn:      false,
    lat:       26.428554,
    lng:       127.827190,
    twitter: "", instagram: "", youtube: "", website: "https://www.family.co.jp/", detailText: "", photos: []
  },
  {
    id:          22,
    code:        "47213-IS-0023",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-05-23",
    name:      "セブンイレブン 石川インター店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川2337",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://seven-eleven.areamarker.com/711map/info/484222?addresscode=47213&shopid=484222",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「ATM・コピー機あり」を削除（登録している出典のいずれにも設備情報の記載がなかったため）" },
      { date: "2026-08-11", type: "ai", note: "sourceUrlを本部の汎用トップページから、セブン-イレブン公式店舗検索（areamarker.com）の店舗固有ページに変更（住所・営業時間の記載が一致することを確認、ユーザーが実際のブラウザ画面で表示を確認）。sourceUrlsのYahoo!地図は除去" }
    ],
    warn:      false,
    lat:       26.434586,
    lng:       127.826263,
    twitter: "", instagram: "", youtube: "", website: "https://www.sej.co.jp/", detailText: "", photos: []
  },
  // ※以下4件のファミマ＋3件のローソンは2026-07-21にOpenStreetMap抽出＋
  //   公式店舗検索等とのウェブ二重照合で追加（座標はOSM、住所・店名は公式等で確認）
  {
    id:          23,
    code:        "47213-IS-0024",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-21",
    name:      "ファミリーマート 石川東山店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川東山1-22-11",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://store.family.co.jp/points/07258",
    warn:      false,
    lat:       26.434764,
    lng:       127.838129,
    twitter: "", instagram: "", youtube: "", website: "https://www.family.co.jp/", detailText: "", photos: []
  },
  {
    id:          24,
    code:        "47213-IS-0025",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-07-21",
    name:      "ファミリーマート 石川白浜店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川白浜2-8-26",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・駐車場あり",
    note_en:   "ATM and parking available.",
    sourceUrl: "https://store.family.co.jp/points/72137",
    revisionHistory: [
      { date: "2026-08-11", type: "ai", note: "sourceUrlをファミリーマート本部の汎用トップページから、この店舗固有の店舗検索ページ（store.family.co.jp/points/72137）に変更（ユーザー指摘。住所・営業時間・ATM/駐車場の記載が一致することを確認）。第三者サイト（homemate-research）はsourceUrlsから除去" }
    ],
    warn:      false,
    lat:       26.424311,
    lng:       127.825500,
    twitter: "", instagram: "", youtube: "", website: "https://www.family.co.jp/", detailText: "", photos: []
  },
  {
    id:          25,
    code:        "47213-IS-0026",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-07-21",
    name:      "ファミリーマート 石川高校前店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川伊波294-1",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://store.family.co.jp/points/72133",
    revisionHistory: [
      { date: "2026-08-11", type: "ai", note: "sourceUrlを本部の汎用トップページから、この店舗固有の店舗検索ページ（store.family.co.jp/points/72133）に変更（住所の記載が一致することを確認）。sourceUrls内のNAVITIMEは複製・転載を禁止する規約があるため除去（石川白浜店での同様の指摘を受け、他のファミマ店舗も一括対応）" }
    ],
    warn:      false,
    lat:       26.415741,
    lng:       127.821848,
    twitter: "", instagram: "", youtube: "", website: "https://www.family.co.jp/", detailText: "", photos: []
  },
  {
    id:          26,
    code:        "47213-IS-0027",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-21",
    name:      "ファミリーマート 石川東恩納店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川東恩納666-1",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://store.family.co.jp/points/72349",
    sourceUrls: ["https://store.family.co.jp/points/72349", "https://www.navitime.co.jp/poi?spot=01155-ofm00000305"],
    warn:      false,
    lat:       26.410708,
    lng:       127.827042,
    twitter: "", instagram: "", youtube: "", website: "https://www.family.co.jp/", detailText: "", photos: []
  },
  {
    id:          27,
    code:        "47213-IS-0028",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-07-21",
    name:      "ローソン 石川バイパス店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川山城842-3",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "駐車場あり",
    note_en:   "Parking available.",
    sourceUrl: "https://www.areamarker.com/lawson/info/241123?addresscode=47213&shopid=241123",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「国道329号石川バイパス沿い・」を削除（出典で確認できたのは駐車場情報のみだったため）" },
      { date: "2026-08-11", type: "ai", note: "sourceUrlを規約違反サイト（e-map.ne.jp）から、ローソン公式店舗検索（areamarker.com）の店舗固有ページに変更（住所・営業時間の記載が一致することを確認）。sourceUrlsのNAVITIMEは除去" }
    ],
    warn:      false,
    lat:       26.412944,
    lng:       127.817921,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },
  {
    id:          28,
    code:        "47213-IS-0029",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-07-21",
    name:      "ローソン うるま石川東恩納店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川東恩納251-1",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・駐車場あり",
    note_en:   "ATM and parking available.",
    sourceUrl: "https://www.areamarker.com/lawson/info/374700?addresscode=47213&shopid=374700",
    revisionHistory: [
      { date: "2026-08-11", type: "ai", note: "sourceUrlを規約違反サイト（e-map.ne.jp）から、ローソン公式店舗検索（areamarker.com）の店舗固有ページに変更（住所・営業時間の記載が一致することを確認）。sourceUrlsのNAVITIMEは除去" }
    ],
    warn:      false,
    lat:       26.414672,
    lng:       127.834395,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },
  {
    id:          29,
    code:        "47213-IS-0030",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-07-21",
    name:      "ローソン うるま伊波店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川伊波1512-15",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・駐車場あり",
    note_en:   "ATM and parking available.",
    sourceUrl: "https://www.areamarker.com/lawson/info/287148?addresscode=47213&shopid=287148",
    revisionHistory: [
      { date: "2026-08-11", type: "ai", note: "sourceUrlを規約違反サイト（e-map.ne.jp）から、ローソン公式店舗検索（areamarker.com）の店舗固有ページに変更（住所・営業時間の記載が一致することを確認）。sourceUrlsのNAVITIMEは除去" }
    ],
    warn:      false,
    lat:       26.426880,
    lng:       127.807813,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },
  // ※以下4件は2026-07-21にサイト管理人の指摘を受けて追加。
  //   OSM未登録だったためチェーン公式店舗検索・複数地図サービスで存在・住所・座標を照合済み
  {
    id:          30,
    code:        "47213-IS-0031",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-07-21",
    name:      "ローソン 石川インター店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川2313-2",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.areamarker.com/lawson/info/269914?addresscode=47213&shopid=269914",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「駐車場あり」を削除（登録している出典に公式な記載がなく、口コミでの言及のみだったため）" },
      { date: "2026-08-11", type: "ai", note: "sourceUrlを規約違反サイト（e-map.ne.jp）から、ローソン公式店舗検索（areamarker.com）の店舗固有ページに変更（住所・営業時間の記載が一致することを確認）。sourceUrlsのYahoo!地図は除去" }
    ],
    warn:      false,
    lat:       26.435600,
    lng:       127.827321,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },
  {
    id:          31,
    code:        "47213-IS-0032",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-07-21",
    name:      "セブンイレブン 石川白浜1丁目店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川白浜1-4-17",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATMあり",
    note_en:   "ATM available.",
    sourceUrl: "https://seven-eleven.areamarker.com/711map/info/510965?addresscode=47213&shopid=510965",
    revisionHistory: [
      { date: "2026-08-11", type: "ai", note: "sourceUrlを本部の汎用トップページから、セブン-イレブン公式店舗検索（areamarker.com）の店舗固有ページに変更（住所・営業時間の記載が一致することを確認）" }
    ],
    warn:      false,
    lat:       26.428954,
    lng:       127.827897,
    twitter: "", instagram: "", youtube: "", website: "https://www.sej.co.jp/", detailText: "", photos: []
  },
  {
    id:          32,
    code:        "47213-IS-0033",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-07-21",
    name:      "セブンイレブン 石川曙2丁目店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川曙2丁目1-38",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://seven-eleven.areamarker.com/711map/info/507526?addresscode=47213&shopid=507526",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "sourceUrlのe-map.ne.jpがリンク切れ（パラメータエラー）だったためYahoo!地図に差し替え。備考「ATMあり」を削除（登録している出典のいずれにも記載がなかったため）" },
      { date: "2026-08-11", type: "ai", note: "sourceUrlを規約違反サイト（Yahoo!地図）から、セブン-イレブン公式店舗検索（areamarker.com）の店舗固有ページに変更（住所・営業時間の記載が一致することを確認）" }
    ],
    warn:      false,
    lat:       26.421245,
    lng:       127.825255,
    twitter: "", instagram: "", youtube: "", website: "https://www.sej.co.jp/", detailText: "", photos: []
  },
  {
    id:          33,
    code:        "47213-IS-0034",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-07-21",
    name:      "ローソン 石川曙三丁目店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川曙3-12-76",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.areamarker.com/lawson/info/286976?addresscode=47213&shopid=286976",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「店内に郵便ポストあり」を削除（登録している出典のいずれにも記載がなかったため）" },
      { date: "2026-08-11", type: "ai", note: "sourceUrlを規約違反サイト（e-map.ne.jp）から、ローソン公式店舗検索（areamarker.com）の店舗固有ページに変更（住所・営業時間の記載が一致することを確認）。sourceUrlsのYahoo!地図は除去" }
    ],
    warn:      false,
    lat:       26.415945,
    lng:       127.824158,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },

  // ── ガソリンスタンド ──────────────────────────────────────────────
  {
    id:          34,
    code:        "47213-IS-0035",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-24",
    name:      "ENEOSサンセール石川インターSS",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川2337",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "石川インター近く。株式会社山城石油が運営",
    note_en:   "Near Ishikawa interchange. Operated by Yamashiro Oil.",
    sourceUrl: "https://eneos-ss.com/search/ss/pc/detail.php?SCODE=987654",
    sourceUrls: ["https://eneos-ss.com/search/ss/pc/detail.php?SCODE=987654"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "sourceUrlをENEOS公式店舗検索（eneos-ss.com）に変更し、規約上安全とは言えないNAVITIMEを除去。営業時間・定休日・運営会社名はENEOS公式ページの記載と完全一致することを確認" }
    ],
    warn:      false,
    lat:       26.434555,
    lng:       127.826689,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          35,
    code:        "47213-IS-0036",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-05-24",
    name:      "伊波SS（神谷石油）",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川伊波309",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://oki-ss.or.jp/?page_id=167",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「営業時間・定休日は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" },
      { date: "2026-08-11", type: "ai", note: "sourceUrlを規約違反サイト（NAVITIME）から、沖縄県石油商業組合公式サイト（oki-ss.or.jp、住所・系列・運営会社名の記載を確認済み）に変更。sourceUrlsのe-nenpi.comは規約違反サイトのため除去" }
    ],
    warn:      true,
    lat:       26.414359,
    lng:       127.823418,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          36,
    code:        "47213-IS-0037",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-05-24",
    name:      "嘉手苅SS（くだか石油）",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川嘉手苅141-6",
    hours:     "要確認",
    closed:    "要確認",
    note:      "カーエネクス系列",
    note_en:   "Carenex brand station.",
    sourceUrl: "https://oki-ss.or.jp/?page_id=167",
    sourceUrls: ["https://oki-ss.or.jp/?page_id=167", "https://gasoline-gift.zensekiren.or.jp/station/4700007001"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考から電話番号「098-965-5565」を削除（変更されうる個別の連絡先情報は転記しない方針としたため）" },
      { date: "2026-08-08", type: "ai", note: "備考「（営業時間・定休日は要確認）」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" },
      { date: "2026-08-11", type: "ai", note: "sourceUrlsから規約違反サイト（e-nenpi.com）を除去" }
    ],
    warn:      true,
    lat:       26.420632,
    lng:       127.813352,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  // ※以下2件は2026-07-24にOSM抽出＋出光公式SS検索/Yahoo!地図/geocoding.jp等との
  // ウェブ複数照合で追加（poi-surveyスキル手順）
  {
    id:          37,
    code:        "47213-IS-0038",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "アポロステーション石川SS（石川サービス）",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川431",
    hours:     "7:00〜20:00",
    closed:    "年中無休",
    note:      "出光系列アポロステーション。セルフ式",
    note_en:   "Idemitsu apollostation brand, self-service.",
    sourceUrl: "https://map.idemitsu.com/b/a/info/0000019740/",
    sourceUrls: ["https://map.idemitsu.com/b/a/info/0000019740/", "https://e-nenpi.com/gs/map/47033", "https://oki-ss.or.jp/?page_id=167"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考から電話番号「098-964-2025」を削除（変更されうる個別の連絡先情報は転記しない方針としたため）" }
    ],
    warn:      false,
    lat:       26.424717,
    lng:       127.825160,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          38,
    code:        "47213-IS-0039",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-07-24",
    name:      "赤崎サービスステーション（瑞穂石油）",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川東山本町2-4-1",
    hours:     "要確認",
    closed:    "要確認",
    note:      "カーエネクス系列",
    note_en:   "Carenex brand station.",
    sourceUrl: "https://oki-ss.or.jp/?page_id=167",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "営業時間を「7:00〜21:00」から「平日 7:00〜21:00 / 日・祝 8:00〜20:00」に修正（出典e-nenpi.comに日曜・祝日は時間が異なる旨の記載があったため）" },
      { date: "2026-08-08", type: "ai", note: "備考から電話番号「098-964-2626」を削除（変更されうる個別の連絡先情報は転記しない方針としたため）" },
      { date: "2026-08-11", type: "ai", note: "sourceUrlを規約違反サイト（Yahoo!地図）から沖縄県石油商業組合公式サイト（oki-ss.or.jp）に変更。同サイトには営業時間の記載がなく、現行の営業時間はe-nenpi.com（規約違反サイト）のみが出典だったため「要確認」に変更。備考「フルサービス（洗車・オイル交換等対応）」も同様に裏付けが取れないため削除、系列情報（カーエネクス）はoki-ss.or.jpで確認できるため維持" }
    ],
    warn:      true,
    lat:       26.434840,
    lng:       127.835272,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },

  // ── テスト用店舗（石川ビーチ沖合・動作確認専用） ─────────────────
  {
    id:          39,
    code:        "47213-IS-0040",
    status:      "test",
    tel:         "",
    lastChecked: "",
    listedDate:  "2026-05-16",
    name:      "【テスト】石川ビーチ海上店",
    genre:     "テスト用",
    address:   "石川ビーチ沖合（テスト用・実在しません）",
    hours:     "テスト営業時間 9:00〜18:00",
    closed:    "テスト定休日",
    note:      "これは動作確認用のテスト店舗です。実在しません。店舗オーナー操作機能の確認に使用します。",
    note_en:   "This is a test store for system verification. Not a real restaurant.",
    sourceUrl: "",
    warn:      false,
    alwaysShow: true,
    lat:       26.4268,
    lng:       127.8415,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "これはテスト用の店舗です。\n\n今後、店舗オーナーが自分で情報を更新・追加できる機能の確認に使用します。\n\n実際の営業はしていません。",
    photos:     []
  },
  // ── 宿泊施設 ───────────────────────────────────────────────────
  {
    id:          40,
    code:        "47213-IS-0041",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-11",
    listedDate:  "2026-05-30",
    name:      "ココ ガーデンリゾート オキナワ",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川伊波501",
    hours:     "チェックイン 14:00〜 / チェックアウト 〜11:00",
    closed:    "年中無休",
    note:      "石川の高台に建つリゾートホテル",
    sourceUrl: "https://cocogarden.com/",
    sourceUrls: ["https://cocogarden.com/", "https://www.okinawastory.jp/stay/1241"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "チェックイン時刻を15:00から14:00に修正、備考の「石川海岸沿いの」を「石川の高台に建つ」に修正（一休.com・Yahoo!トラベル・じゃらんnet等の複数の予約サイトで確認。ビーチは姉妹ホテルへの無料シャトルバスで利用する提携形式）" },
      { date: "2026-08-11", type: "ai", note: "公式サイト（cocogarden.com）にSSL証明書エラーが発生しており直接アクセスできなかったため、検索エンジンのインデックス・スニペット経由で間接的に再確認。チェックイン14:00・チェックアウト11:00は公式サイトのFAQページ（cocogarden.com/faq/）のスニペットと、「石川の高台に建つ」は「伊波城跡の敷地・石川高台に位置」という記述と、それぞれ一致することを確認。年中無休の直接的な裏付けは今回見つからず（既存記載を維持）" },
      { date: "2026-08-11", type: "ai", note: "sourceUrlsから規約違反サイト（じゃらんnet）を除去（利用規約に複製・転載禁止条項を確認したため）" }
    ],
    warn:      false,
    lat:       26.42030,
    lng:       127.81988
  },
  {
    id:          41,
    code:        "47213-IS-0042",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-05",
    listedDate:  "2026-08-05",
    name:      "ANAクラウンプラザリゾート沖縄うるまヒルズ",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川山城1468",
    hours:     "チェックイン 15:00〜 / チェックアウト 〜12:00",
    closed:    "年中無休",
    note:      "旧「アンサ沖縄リゾート」。2024年12月にIHG・ANAホールディングスが運営受託契約を締結し、2025年初頭にリブランド",
    note_en:   "Formerly \"ANSA Okinawa Resort\". Rebranded in early 2025 after IHG and ANA Holdings signed a hotel management agreement in December 2024.",
    sourceUrl: "https://uruma-ru.jp/member/anacrownepl/",
    sourceUrls: ["https://uruma-ru.jp/member/anacrownepl/", "https://www.sports-commission.okinawa/en/hotel/h-51403/"],
    revisionHistory: [
      { date: "2026-08-05", type: "ai", note: "店名を「アンサ沖縄リゾート」から「ANAクラウンプラザリゾート沖縄うるまヒルズ」に変更、チェックアウト時刻を11:00から12:00に修正（住所・電話番号098-963-0123は変更前と一致、複数ソースで確認）" }
    ],
    warn:      false,
    lat:       26.41774,
    lng:       127.79255,
    website:   "https://www.ihg.com/crowneplaza/hotels/jp/ja/okinawa/okaou/hoteldetail"
  },
  {
    id:          42,
    code:        "47213-IS-0043",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-30",
    name:      "民宿レキオ",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川2-26-4",
    hours:     "チェックイン 16:00〜 / チェックアウト 〜10:00",
    closed:    "要確認",
    note:      "石川エリアの民宿",
    sourceUrl: "http://www.lequio7.sakura.ne.jp/",
    sourceUrls: ["http://www.lequio7.sakura.ne.jp/", "https://www.ekiten.jp/shop_2457906/", "https://travel.rakuten.co.jp/HOTEL/167138/review.html"],
    warn:      true,
    lat:       26.42586,
    lng:       127.82483
  },
  {
    id:          43,
    code:        "47213-IS-0044",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-30",
    name:      "民宿やすま",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川曙2丁目3-1",
    hours:     "チェックイン 16:00〜 / チェックアウト 〜10:00",
    closed:    "要確認",
    note:      "石川エリアの民宿",
    sourceUrl: "https://www.ekiten.jp/shop_2457905/",
    sourceUrls: ["https://www.ekiten.jp/shop_2457905/"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "情報源のうち「https://uruma-ru.jp/stay/」を削除（掲載されている宿泊施設一覧に「民宿やすま」が含まれていないことを確認したため）" }
    ],
    warn:      true,
    lat:       26.42059,
    lng:       127.82524
  },
  // ── 金融機関 ───────────────────────────────────────────────────
  {
    id:          44,
    code:        "47213-IS-0045",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-30",
    name:      "琉球銀行 石川支店",
    genre:     "金融",
    address:   "沖縄県うるま市石川2-23-6",
    hours:     "平日 9:00〜15:00",
    closed:    "土・日・祝日",
    note:      "ATMは時間外も利用可",
    sourceUrl: "https://www.ryugin.co.jp/tenpo/atm_search/shop-5030/",
    warn:      false,
    lat:       26.42626,
    lng:       127.82578
  },
  {
    id:          45,
    code:        "47213-IS-0046",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-30",
    name:      "沖縄銀行 石川支店",
    genre:     "金融",
    address:   "沖縄県うるま市石川2丁目24-1",
    hours:     "平日 9:00〜11:30、12:30〜15:00（昼休みを除く）",
    closed:    "土・日・祝日",
    note:      "ATMは時間外も利用可",
    sourceUrl: "https://www.okinawa-bank.co.jp/shop_atm/2014061100881/",
    sourceUrls: ["https://www.okinawa-bank.co.jp/shop_atm/2014061100881/", "https://gincode.com/branch_0188_315"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "営業時間を「平日9:00〜15:00」から「平日9:00〜11:30、12:30〜15:00（昼休みを除く）」に修正（出典の公式サイトに昼休み11:30〜12:30は窓口が閉まる旨の記載があったため）。sourceUrlを情報の薄いgincode.comから公式サイトに変更" }
    ],
    warn:      false,
    lat:       26.42580,
    lng:       127.82557
  },
  {
    id:          46,
    code:        "47213-IS-0047",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-30",
    name:      "石川郵便局",
    genre:     "金融",
    address:   "沖縄県うるま市石川東山本町1-1-2",
    hours:     "郵便 平日9:00〜17:00 / 貯金 平日9:00〜16:00",
    closed:    "土・日・祝日",
    note:      "",
    sourceUrl: "https://map.japanpost.jp/p/search/dtl/300170031000/",
    sourceUrls: ["https://map.japanpost.jp/p/search/dtl/300170031000/"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "備考「ATMあり（土日も利用可）」を削除（登録している出典2件のいずれにもATM稼働時間・土日利用可否の記載が確認できなかったため）" },
      { date: "2026-08-08", type: "ai", note: "sourceUrlsから規約違反サイト（Yahoo!地図）を除去。日本郵便公式サイト（map.japanpost.jp）に改めてアクセスし、営業時間・定休日とも現行データと一致することを再確認" }
    ],
    warn:      false,
    lat:       26.43363,
    lng:       127.83207
  },
  // ── 教育施設 ───────────────────────────────────────────────────
  {
    id:          47,
    code:        "47213-IS-0048",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-30",
    name:      "うるま市立宮森小学校",
    genre:     "教育",
    address:   "沖縄県うるま市石川1丁目46-1",
    hours:     "平日 8:15〜16:45（登校日）",
    closed:    "土・日・祝日",
    note:      "",
    sourceUrl: "https://www.city.uruma.lg.jp/3001002000/shisetsu/p000051.html",
    sourceUrls: ["https://www.city.uruma.lg.jp/3001002000/shisetsu/p000051.html", "https://www.city.uruma.lg.jp/", "https://www.mapion.co.jp/phonebook/M11006/47213/ILSP0000077493_ipclm/"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "営業時間を「8:00〜17:00」から「8:15〜16:45」に修正、定休日から出典に記載のない「・長期休暇」を削除（うるま市公式サイトの個別ページp000051.htmlの記載に合わせ、sourceUrlにも同ページを追加）" }
    ],
    warn:      false,
    lat:       26.43175,
    lng:       127.82759
  },
  {
    id:          48,
    code:        "47213-IS-0049",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-30",
    name:      "うるま市立石川中学校",
    genre:     "教育",
    address:   "沖縄県うるま市石川440番地1",
    hours:     "平日 8:15〜16:45（登校日）",
    closed:    "土・日・祝日・長期休暇",
    note:      "",
    sourceUrl: "https://j-ishikawa.edu.city.uruma.okinawa.jp/",
    sourceUrls: ["https://j-ishikawa.edu.city.uruma.okinawa.jp/", "https://www.city.uruma.lg.jp/3001002000/shisetsu/p000066.html"],
    revisionHistory: [
      { date: "2026-08-06", type: "ai", note: "営業時間を「8:00〜17:00」から「8:15〜16:45」に修正（うるま市公式サイトの記載に合わせた）" }
    ],
    warn:      false,
    lat:       26.42399,
    lng:       127.82429
  },
  {
    id:          49,
    code:        "47213-IS-0050",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-30",
    name:      "沖縄県立石川高等学校",
    genre:     "教育",
    address:   "沖縄県うるま市石川伊波861",
    hours:     "要確認",
    closed:    "要確認",
    note:      "普通科",
    sourceUrl: "https://www.ishikawa-h.open.ed.jp/",
    sourceUrls: ["https://www.ishikawa-h.open.ed.jp/", "https://ja.wikipedia.org/wiki/沖縄県立石川高等学校"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "開庁時間「平日8:00〜17:00」を「要確認」に変更（登録している出典（学校公式サイト・Wikipedia・県教育委員会ページ）のいずれにも記載がなく、他の市立校で同じ値が誤りだった前例があるため、裏付けのないまま掲載を続けるのは避けた）。noteの「普通科」は出典で確認済みのため維持" },
      { date: "2026-08-08", type: "ai", note: "備考「。営業時間・定休日は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" }
    ],
    warn:      true,
    lat:       26.41535,
    lng:       127.82052
  },
  // ── 観光スポット ───────────────────────────────────────────────
  {
    id:          50,
    code:        "47213-IS-0051",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-06",
    listedDate:  "2026-05-30",
    name:      "石川ビーチ（石川公園）",
    genre:     "観光",
    address:   "沖縄県うるま市石川白浜2丁目11-1",
    hours:     "年中無休（自由）",
    closed:    "なし",
    note:      "地元市民に親しまれている市民ビーチ。管理団体がいないため遊泳等の利用は自己責任。監視員・クラゲ防止ネットの有無など現地の状況をご確認のうえご利用ください",
    revisionHistory: [
      { date: "2026-08-05", type: "ai", note: "住所を「沖縄県うるま市石川曙」から「沖縄県うるま市石川白浜2丁目11-1」に修正（出典自体とも不一致だったため。うるま市公式サイト・おきなわ物語で確認。座標付近は字境をまたぎ「石川石崎」表記の情報源もある）" },
      { date: "2026-08-05", type: "ai", note: "備考「リーフ内は砂地で安全」を削除。出典（okinawastory.jp）に該当記載がなく、別サイトの類似文言との混同が疑われるため。海は条件によらず危険を伴うため「安全」の断定表現を避け、注意喚起の文言に変更" },
      { date: "2026-08-05", type: "ai", note: "備考「ウィンドサーフィンで有名な」を削除。okinawastory.jp・tagoo.jp・沖縄県公式・churatown.comの4件を実際に確認したがいずれにも記載がなく、実態とも合わないとの指摘があったため。okinawastory.jpで確認できた「地元市民に親しまれている」に基づく表現に変更" },
      { date: "2026-08-06", type: "ai", note: "備考「遊泳の際は現地の掲示・気象情報をご確認のうえご注意ください」を削除。この文言は出典（okinawastory.jp）に存在せず、AIが独自に言い換えた注意喚起文だったため、出典に実際に記載されている注意事項（「管理している団体等がいないため、遊泳等の利用については自己責任。監視員およびクラゲ防止ネットの有無など、現地の状況をご確認の上、ご利用の際は安全にご注意ください」）に基づく表現に修正" }
    ],
    sourceUrl: "https://www.okinawastory.jp/spot/600006184",
    sourceUrls: ["https://www.okinawastory.jp/spot/600006184", "https://www.city.uruma.lg.jp/1009007000/shisetsu/p000141.html"],
    warn:      false,
    lat:       26.42574,
    lng:       127.82849
  },
  {
    id:          51,
    code:        "47213-IS-0052",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-05-30",
    name:      "石川岳（市民の森公園）",
    genre:     "観光",
    address:   "沖縄県うるま市石川",
    hours:     "年中無休（自由）",
    closed:    "なし",
    note:      "標高204m。山頂展望台から太平洋と東シナ海を一望できる",
    sourceUrl: "https://www.city.uruma.lg.jp/miryoku/p000001.html",
    sourceUrls: ["https://www.city.uruma.lg.jp/miryoku/p000001.html", "https://uruma-portal.okinawa/archives/832"],
    warn:      false,
    lat:       26.44810,
    lng:       127.83208
  },

  // ── 美容・理容 ─────────────────────────────────────────────────
  // ※以下16件は2026-07-24にOSM抽出＋公式サイト/Yahoo!地図/エキテン等との
  // ウェブ複数照合（Agentツールによる並行検証）で追加
  {
    id:          52,
    code:        "47213-IS-0053",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-10",
    listedDate:  "2026-07-24",
    name:      "エステサロンDOUBLE（ダブル）",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川830-10",
    hours:     "10:00〜18:00",
    closed:    "日・月・祝日",
    note:      "エステサロン（脱毛・フェイシャル等）",
    note_en:   "Esthetic salon (hair removal, facial, etc.).",
    sourceUrl: "http://double-esthetic.com/contact.html",
    sourceUrls: ["http://double-esthetic.com/contact.html", "https://double201551.ti-da.net/"],
    revisionHistory: [
      { date: "2026-08-10", type: "ai", note: "備考「国道329号(石川バイパス)沿い」を削除（2026-07-24のAgent調査で追加された記述だが、公式サイト・座標の逆ジオコーディングいずれでも裏付けが取れず、AIが推測で書いた可能性が高いと判断したため）。sourceUrlを公式サイトの該当ページ（contact.html、営業時間・定休日の記載を確認済み）に変更し、規約違反サイトであるYahoo!地図をsourceUrlsから除去" }
    ],
    warn:      false,
    lat:       26.425014,
    lng:       127.820172,
    twitter: "", instagram: "", youtube: "", website: "http://double-esthetic.com/", detailText: "", photos: []
  },
  {
    id:          53,
    code:        "47213-IS-0054",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "IWASAKI沖縄石川店",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川1-16-1 マックスバリュ石川店1階",
    hours:     "10:00〜19:00",
    closed:    "年中無休",
    note:      "全国展開の美容室チェーン。マックスバリュ石川店1階",
    note_en:   "Nationwide hair salon chain IWASAKI, inside MaxValu Ishikawa store.",
    sourceUrl: "https://hkbn.co.jp/iwasaki/salon/list.php?pname=%E6%B2%96%E7%B8%84",
    sourceUrls: ["https://hkbn.co.jp/iwasaki/salon/list.php?pname=%E6%B2%96%E7%B8%84", "https://riyou.jp/shop/96183/"],
    warn:      false,
    lat:       26.430901,
    lng:       127.824645,
    twitter: "", instagram: "", youtube: "", website: "https://hkbn.co.jp/iwasaki/", detailText: "", photos: []
  },
  {
    id:          54,
    code:        "47213-IS-0055",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "IWASAKI沖縄赤崎店",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川赤崎2-1-1 サンエー赤崎店1階",
    hours:     "9:00〜18:00",
    closed:    "年中無休",
    note:      "全国展開の美容室チェーン。サンエー赤崎店1階",
    note_en:   "Nationwide hair salon chain IWASAKI, inside Sun-A Akasaki store.",
    sourceUrl: "https://hkbn.co.jp/iwasaki/salon/list.php?pname=%E6%B2%96%E7%B8%84",
    sourceUrls: ["https://hkbn.co.jp/iwasaki/salon/list.php?pname=%E6%B2%96%E7%B8%84", "https://riyou.jp/shop/96196/", "https://map.yahoo.co.jp/v3/place/Ud_QZ2rnhEg"],
    warn:      false,
    lat:       26.433345,
    lng:       127.834342,
    twitter: "", instagram: "", youtube: "", website: "https://hkbn.co.jp/iwasaki/", detailText: "", photos: []
  },
  {
    id:          55,
    code:        "47213-IS-0056",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "でいご理容館",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川1-52-36",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.navitime.co.jp/category/0402003/47213/",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「営業時間・定休日は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" },
      { date: "2026-08-08", type: "ai", note: "代替の公式サイト・公式SNSを調査したが見つからなかった。既に営業時間・定休日は「要確認」のため内容の変更なし。sourceUrl（NAVITIME）は複製・転載を禁止する規約があるため出典としては扱わず、実在確認の手がかりとしてのみ残置" }
    ],
    warn:      true,
    lat:       26.431154,
    lng:       127.829367,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          56,
    code:        "47213-IS-0057",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "ヘアークラブイシトコ",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川1-27-25",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.navitime.co.jp/category/0402003/47213/",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「営業時間・定休日は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" },
      { date: "2026-08-08", type: "ai", note: "代替の公式サイト・公式SNSを調査したが見つからなかった。既に営業時間・定休日は「要確認」のため内容の変更なし。sourceUrl（NAVITIME）は複製・転載を禁止する規約があるため出典としては扱わず、実在確認の手がかりとしてのみ残置" }
    ],
    warn:      true,
    lat:       26.429498,
    lng:       127.827762,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          57,
    code:        "47213-IS-0058",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "クイン美容室",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川2丁目20-1",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://map.yahoo.co.jp/v3/place/Xu8xLHpHHrw",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「営業時間・定休日は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" },
      { date: "2026-08-08", type: "ai", note: "代替の公式サイト・公式SNSを調査したが見つからなかった。既に営業時間・定休日は「要確認」のため内容の変更なし。sourceUrl（Yahoo!地図）は複製・転載を禁止する規約があるため出典としては扱わず、実在確認の手がかりとしてのみ残置" }
    ],
    warn:      true,
    lat:       26.427057,
    lng:       127.825151,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          58,
    code:        "47213-IS-0059",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "ごとう美容室",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川2丁目9-1",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://map.yahoo.co.jp/v3/place/iocOXHLAbSY",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「老舗」を削除（登録している出典に該当する記載がなかったため）" },
      { date: "2026-08-08", type: "ai", note: "備考「。営業時間・定休日は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" },
      { date: "2026-08-08", type: "ai", note: "代替の公式サイト・公式SNSを調査したが見つからなかった。備考「個人経営の美容室」はYahoo!地図由来で裏付けが取れないため削除（同サイトは複製・転載を禁止する規約があり出典として扱わない方針としたため）" }
    ],
    warn:      true,
    lat:       26.428814,
    lng:       127.823964,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          59,
    code:        "47213-IS-0060",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "ヘアーサロンジピー（ZiPPi）",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川白浜1丁目3-7",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.ekiten.jp/shop_2457063/",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "エキテンは複製・転載を禁止する規約があるため転記元から除外することとし、同サイトのみに依存していた営業時間・定休日を「要確認」に変更。代替の公式サイト・公式SNSは調査したが見つからなかった。リンク自体は発見の手がかりとして残置" }
    ],
    warn:      true,
    lat:       26.427888,
    lng:       127.827134,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          60,
    code:        "47213-IS-0061",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "カッティングハウスニューバニー3",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川白浜1丁目3-1",
    hours:     "11:00〜17:00（完全予約制）",
    closed:    "火曜日",
    note:      "",
    note_en:   "",
    sourceUrl: "https://newbunny3.com/about/",
    sourceUrls: ["https://newbunny3.com/about/", "https://map.yahoo.co.jp/v3/place/5mC8cHKH_sc"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "営業時間「要確認」を「11:00〜17:00（完全予約制）」に、定休日「要確認」を「火曜日」に更新（登録済みの公式サイトsourceUrlに既に記載があった）" }
    ],
    warn:      false,
    lat:       26.427557,
    lng:       127.827117,
    twitter: "", instagram: "", youtube: "", website: "https://newbunny3.com/", detailText: "", photos: []
  },
  {
    id:          61,
    code:        "47213-IS-0062",
    status:      "published",
    tel:         "",
    lastChecked: "2026-07-29",
    listedDate:  "2026-07-24",
    name:      "シルバー美容室",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川白浜1丁目2-7",
    hours:     "9:30〜18:00",
    closed:    "毎週火曜日・最終週の月曜日",
    note:      "美容・着付け専門店",
    note_en:   "Hair salon and kimono dressing specialist. Please confirm hours and holidays before visiting.",
    sourceUrl: "https://silver-hairmake.com/about/",
    sourceUrls: ["https://silver-hairmake.com/about/", "https://map.yahoo.co.jp/v3/place/03M-Nahf_U6"],
    warn:      false,
    lat:       26.427684,
    lng:       127.827421,
    twitter: "", instagram: "", youtube: "", website: "https://silver-hairmake.com/", detailText: "", photos: []
  },
  {
    id:          62,
    code:        "47213-IS-0063",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-09",
    listedDate:  "2026-07-24",
    name:      "ゆたか美容室",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川2丁目22-9",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.yelp.com/biz/%E3%82%86%E3%81%9F%E3%81%8B%E7%BE%8E%E5%AE%B9%E5%AE%A4-%E3%81%86%E3%82%8B%E3%81%BE%E5%B8%82",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「営業時間・定休日は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" },
      { date: "2026-08-09", type: "ai", note: "sourceUrl（Yelp）の利用規約にスクレイピング・自動収集を禁止する条項を確認（規約違反サイトと確定）。既に営業時間・定休日は「要確認」のため内容の変更なし。代替の公式サイト・公式SNSも調査したが見つからなかった。リンク自体は発見の手がかりとして残置" }
    ],
    warn:      true,
    lat:       26.426258,
    lng:       127.825554,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          63,
    code:        "47213-IS-0064",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-08-05",
    name:      "pono 石川店（ポノ）",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川2丁目39-8",
    hours:     "要確認",
    closed:    "要確認",
    note:      "旧店名「スィートハンズ石川店」",
    note_en:   "Formerly known as \"Sweet Hands Ishikawa\".",
    revisionHistory: [
      { date: "2026-08-05", type: "ai", note: "店名を「スィートハンズ石川店」から「pono 石川店」に変更（公式サイト・ホットペッパービューティー・Instagramで確認。住所・電話番号098-964-7717は変更前と一致）" },
      { date: "2026-08-08", type: "ai", note: "備考「。営業時間・定休日は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" }
    ],
    sourceUrl: "https://www.ekiten.jp/shop_2456829/",
    sourceUrls: ["https://www.ekiten.jp/shop_2456829/", "https://www.sweethands.net/salon/ishikawa/"],
    warn:      true,
    lat:       26.427584,
    lng:       127.821506,
    twitter: "", instagram: "", youtube: "", website: "https://www.sweethands.net/salon/ishikawa/", detailText: "", photos: []
  },
  {
    id:          64,
    code:        "47213-IS-0065",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "夢咲美容室",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川東山1丁目12-11",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.ekiten.jp/shop_3616835/",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「営業時間・定休日は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" },
      { date: "2026-08-08", type: "ai", note: "代替の公式サイト・公式SNSを調査したが見つからなかった（同名のFacebookページはヒットしたが住所等の関連性を確認できず不採用）。既に営業時間・定休日は「要確認」のため内容の変更なし。sourceUrl（エキテン）は複製・転載を禁止する規約があるため出典としては扱わず、実在確認の手がかりとしてのみ残置" }
    ],
    warn:      true,
    lat:       26.435215,
    lng:       127.831579,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          65,
    code:        "47213-IS-0066",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "美容室さえら",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川東恩納44-1",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.ekiten.jp/shop_2457849/",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「営業時間・定休日は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" },
      { date: "2026-08-08", type: "ai", note: "代替の公式サイト・公式SNSを調査したが見つからなかった。既に営業時間・定休日は「要確認」のため内容の変更なし。sourceUrl（エキテン）は複製・転載を禁止する規約があるため出典としては扱わず、実在確認の手がかりとしてのみ残置" }
    ],
    warn:      true,
    lat:       26.409203,
    lng:       127.828656,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          66,
    code:        "47213-IS-0067",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "グランディール",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川東恩納721-2",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://map.yahoo.co.jp/v3/place/NSvKcDoNksY",
    sourceUrls: ["https://map.yahoo.co.jp/v3/place/NSvKcDoNksY", "https://www.ekiten.jp/shop_7003915/"],
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "Yahoo!地図・エキテンは複製・転載を禁止する規約があるため転記元から除外することとし、両サイトのみに依存していた営業時間・定休日を「要確認」に変更。代替の公式サイト・公式SNSは調査したが見つからなかった（同名別法人〈静岡県富士宮市〉のInstagramはヒットしたが無関係と判断し除外）" }
    ],
    warn:      true,
    lat:       26.413455,
    lng:       127.823629,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          67,
    code:        "47213-IS-0068",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "カットハウスIN",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川伊波810",
    hours:     "要確認",
    closed:    "要確認",
    note:      "",
    note_en:   "",
    sourceUrl: "https://map.yahoo.co.jp/v3/place/gor1YPjRz3M",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「営業時間・定休日は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" },
      { date: "2026-08-08", type: "ai", note: "代替の公式サイト・公式SNSを調査したが見つからなかった。既に営業時間・定休日は「要確認」のため内容の変更なし。sourceUrl（Yahoo!地図）は複製・転載を禁止する規約があるため出典としては扱わず、実在確認の手がかりとしてのみ残置" }
    ],
    warn:      true,
    lat:       26.41725,
    lng:       127.81932,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  // ※以下1件はOSM・ウェブ検索いずれでも発見できず、2026-07-24にユーザーが
  // Googleマップの現地写真で発見。住所・電話番号はウェブ複数照合で確認済みだが、
  // 店名変更（旧「ヘアープロジェクトサヴァ」）はウェブ上で未確認のため要確認扱い
  {
    id:          68,
    code:        "47213-IS-0069",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-08",
    listedDate:  "2026-07-24",
    name:      "セントジェームス石川店",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川2丁目1-7",
    hours:     "要確認",
    closed:    "要確認",
    note:      "旧店名「ヘアープロジェクトサヴァ」。店名変更は現地看板で確認",
    note_en:   "Formerly known as \"Hair Project Sava\". Name change confirmed on-site.",
    sourceUrl: "https://www.ekiten.jp/g0202/a47213/",
    revisionHistory: [
      { date: "2026-08-08", type: "ai", note: "備考「、詳細は要確認」を削除（hours/closedフィールド自体が自動で⚠️表示されるため、noteでの重複記載をやめる方針としたため）" },
      { date: "2026-08-08", type: "ai", note: "チェーンとしての実在は確認できたが（沖縄県内に複数店舗）、石川店固有の公式サイト・公式SNSは見つからなかった。既に営業時間・定休日は「要確認」のため内容の変更なし。sourceUrl（エキテン）は複製・転載を禁止する規約があるため出典としては扱わず、実在確認の手がかりとしてのみ残置" }
    ],
    warn:      true,
    lat:       26.427074,
    lng:       127.826201,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },

  // ── 観光（追加分）─────────────────────────────────────────────
  // ※以下1件は2026-08-02に追加。「石川について」ページ作成中に発見。
  // 実在・住所・電話・開館時間はうるま市公式サイトと沖縄観光情報WEBサイト
  // 「おきなわ物語」（沖縄観光コンベンションビューロー）で一致を確認。
  // 座標はOSM(node/1068017752)を採用し、国土地理院の住所検索と31m以内で一致。
  {
    id:          69,
    code:        "47213-IS-0070",
    status:      "published",
    tel:         "098-965-3866",
    lastChecked: "2026-08-02",
    listedDate:  "2026-08-03",
    name:      "うるま市立石川歴史民俗資料館",
    genre:     "観光",
    address:   "沖縄県うるま市石川曙2丁目1-55",
    hours:     "9:00〜17:00（最終入館16:30）",
    closed:    "月曜（祝祭日と重なる場合は翌日）、祝祭日の翌日、年末年始（12月29日〜1月3日）",
    note:      "入館無料。石川図書館の2階。戦争・収容所関係資料、復元した規格住宅、宮森ジェット機墜落事故の関連資料などを展示。駐車場20台",
    note_en:   "Free admission. On the 2nd floor of Ishikawa Library. Exhibits cover the postwar civilian camp, a restored standard house, and the 1959 Miyamori jet crash.",
    sourceUrl: "https://www.city.uruma.lg.jp/bunka/1282.html",
    sourceUrls: ["https://www.city.uruma.lg.jp/bunka/1282.html", "https://www.okinawastory.jp/spot/20100300"],
    revisionHistory: [
      { date: "2026-08-11", type: "ai", note: "sourceUrlsから規約違反サイト（じゃらんnet）を除去（利用規約に複製・転載禁止条項を確認したため）" }
    ],
    warn:      false,
    lat:       26.421856,
    lng:       127.825245,
    twitter: "", instagram: "", youtube: "", website: "https://www.city.uruma.lg.jp/bunka/1282.html", detailText: "", photos: []
  },

  // ── 観光・教育（追加分）───────────────────────────────────────
  // ※以下4件は2026-08-03に追加。「石川について」ページ作成時のarea-profile調査
  // （うるま市教育委員会リーフレット・市公式サイト）で見つかった候補をOSM抽出＋
  // ウェブ複数照合で検証。座標は国土地理院の住所検索とOSMを突合（詳細は各note参照）。
  // 同時に見つかった以下は住所・座標の確証が取れず今回は保留：
  // 伊波貝塚（国指定史跡、大字レベルの住所のみで特定不可）、
  // 沖縄諮詢会堂跡・石川部落事務所（市指定文化財、住所情報が見つからず/一部で
  // 資料館と同一住所という疑わしい情報のみ）、エナジックスタジアム石川
  // （住所表記がサイトごとに揺れ、国土地理院とOSMの座標が232m離れ不一致）。
  {
    id:          70,
    code:        "47213-IS-0071",
    status:      "published",
    tel:         "098-964-4888",
    lastChecked: "2026-08-03",
    listedDate:  "2026-08-03",
    name:      "CAVE OKINAWA",
    genre:     "観光",
    address:   "沖縄県うるま市石川嘉手苅479-1",
    hours:     "9:00〜17:30（最終入場17:00）。夏季延長期間は18:30まで（最終入場18:00）",
    closed:    "年中無休",
    note:      "全長200mの鍾乳洞。大人1,200円・子供600円・幼児無料。無料駐車場70台。石川ICから車で約5分",
    note_en:   "A 200m limestone cave. Adults ¥1,200, children ¥600, infants free. Free parking (70 spaces).",
    sourceUrl: "https://www.cave.okinawa/",
    sourceUrls: ["https://www.cave.okinawa/", "https://www.okinawastory.jp/spot/600010161"],
    warn:      false,
    lat:       26.422075,
    lng:       127.807503,
    twitter: "", instagram: "", youtube: "", website: "https://www.cave.okinawa/", detailText: "", photos: []
  },
  {
    id:          71,
    code:        "47213-IS-0072",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-03",
    listedDate:  "2026-08-03",
    name:      "伊波城跡",
    genre:     "観光",
    address:   "沖縄県うるま市石川伊波",
    hours:     "見学自由",
    closed:    "なし",
    note:      "県指定史跡。標高87mの伊波丘陵にあるグスク跡。座標はOSM登録のみで住所ベースの裏取りは大字レベルまで（要確認の範囲は数十m程度）",
    note_en:   "A prefecturally designated historic castle site atop the 87m Iha hill.",
    sourceUrl: "https://www.okinawastory.jp/spot/30000101",
    warn:      true,
    warnReason: "coords",
    lat:       26.421474,
    lng:       127.817138,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          72,
    code:        "47213-IS-0073",
    status:      "published",
    tel:         "098-923-7612",
    lastChecked: "2026-08-03",
    listedDate:  "2026-08-03",
    name:      "石川多目的ドーム",
    genre:     "観光",
    address:   "沖縄県うるま市石川2298-1",
    hours:     "見学自由（闘牛大会は年25回ほど開催、日程は公式サイト参照）",
    closed:    "なし",
    note:      "県内唯一の全天候型闘牛場。2007年完成。うるま市は全国で初めて「闘牛のまち」を宣言。座標は市公式サイト記載値とOSMが7m以内で一致",
    note_en:   "Okinawa's only all-weather bullfighting arena, completed in 2007.",
    sourceUrl: "https://www.city.uruma.lg.jp/1007003000/shisetsu/p000260.html",
    warn:      false,
    lat:       26.436185,
    lng:       127.825552,
    twitter: "", instagram: "", youtube: "", website: "https://www.city.uruma.lg.jp/1007003000/shisetsu/p000260.html", detailText: "", photos: []
  },
  {
    id:          73,
    code:        "47213-IS-0074",
    status:      "published",
    tel:         "098-964-2086",
    lastChecked: "2026-08-03",
    listedDate:  "2026-08-03",
    name:      "うるま市立城前小学校",
    genre:     "教育",
    address:   "沖縄県うるま市石川400",
    hours:     "平日 8:00〜17:00（登校日）",
    closed:    "土・日・祝日・長期休暇",
    note:      "戦後最初の学校「石川学園」の流れをくむ学校。校内に「戦後教育発祥之地」の碑がある",
    sourceUrl: "https://www.city.uruma.lg.jp/3001002000/shisetsu/p000050.html",
    sourceUrls: ["https://www.city.uruma.lg.jp/3001002000/shisetsu/p000050.html", "https://www.pref.okinawa.jp/edu/shien/gakko/sho/144.html"],
    warn:      false,
    lat:       26.424265,
    lng:       127.822790,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  }
];
