// ── 店舗データ ─────────────────────────────────────────────────
// detail.html と script.js の両方から読み込む共通データファイル
const restaurants = [
  {
    name:      "酒楽場うまし家",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川1丁目28-18",
    hours:     "17:00〜翌1:00",
    closed:    "火曜日",
    note:      "創業40年超。石川社交街の老舗大衆居酒屋。県産無農薬野菜使用",
    note_en:   "Over 40 years in business. A long-established izakaya in Ishikawa's entertainment district. Uses locally grown organic vegetables.",
    sourceUrl: "https://umashiya.com/about/",
    warn:      false,
    lat:       26.430443,
    lng:       127.828701,
    // 詳細ページ用フィールド
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "https://umashiya.com/",
    detailText: "",
    photos:     []
  },
  {
    name:      "クリームソーダ",
    genre:     "バル（中華・和食・バー）",
    address:   "沖縄県うるま市石川白浜1-2-1 2F",
    hours:     "中華ランチ：月・木・金 11:30〜14:00\nBAR：年中無休 18:00〜\n中華ディナー：土・日 18:00〜21:00",
    closed:    "不定休",
    note:      "営業スタイルが複雑。訪問前に公式サイトで要確認",
    note_en:   "Complex schedule. Please check the official site before visiting.",
    sourceUrl: "https://balcreamsoda.com/",
    warn:      false,
    lat:       26.427302,
    lng:       127.827541,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "https://balcreamsoda.com/",
    detailText: "",
    photos:     []
  },
  {
    name:      "杏屋 石川店",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川白浜1-4-7",
    hours:     "18:00〜翌3:00（料理L.O. 翌1:45）",
    closed:    "なし（年中無休）",
    note:      "深夜営業。個室あり。飲み放題コースあり",
    note_en:   "Late-night hours. Private rooms available. All-you-can-drink courses offered.",
    sourceUrl: "https://www.hotpepper.jp/strJ001017974/",
    warn:      false,
    lat:       26.428326,
    lng:       127.827701,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "牛角 うるま石川店",
    genre:     "焼肉",
    address:   "沖縄県うるま市石川1-16-18",
    hours:     "16:00〜23:00",
    closed:    "年中無休",
    note:      "チェーン店（牛角グループ）",
    note_en:   "Chain restaurant (Gyukaku group).",
    sourceUrl: "https://map.reins.co.jp/gyukaku/detail/989653529",
    warn:      false,
    lat:       26.431203,
    lng:       127.825063,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "Capful（キャプフル）",
    genre:     "カフェ",
    address:   "沖縄県うるま市石川曙1丁目6-1",
    hours:     "7:30〜15:30（月〜木）\n7:30〜21:00（金・土・日）",
    closed:    "水曜日",
    note:      "元外国人住宅を改装。海が見えるテラス席。朝食営業あり",
    note_en:   "Renovated former US military housing. Terrace seating with ocean view. Breakfast available.",
    sourceUrl: "https://www.instagram.com/okinawa_capful/",
    warn:      false,
    lat:       26.420088,
    lng:       127.828450,
    twitter:    "",
    instagram:  "https://www.instagram.com/okinawa_capful/",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "HINA CAFE（ヒナカフェ）",
    genre:     "カフェ・イタリアン",
    address:   "沖縄県うるま市石川白浜1-1-1 2F",
    hours:     "ランチ 11:30〜15:30\nディナー（金〜日）16:00〜22:00",
    closed:    "月〜水曜日",
    note:      "2023年6月オープン。本格イタリアン",
    note_en:   "Opened June 2023. Authentic Italian cuisine.",
    sourceUrl: "https://hitosara.com/0004038163/",
    warn:      false,
    lat:       26.427231,
    lng:       127.827883,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "GENCO（ジェンコ）",
    genre:     "カフェ・バー（ハワイ料理）",
    address:   "沖縄県うるま市石川伊波1515-32",
    hours:     "11:11〜15:00 / 17:00〜23:00",
    closed:    "火曜日",
    note:      "食べログに営業状況「未確認」の記載あり。訪問前に電話確認を推奨（098-988-5863）",
    note_en:   "Listed as 'unconfirmed' on Tabelog. Recommended to call ahead before visiting (098-988-5863).",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47031510/",
    warn:      true,
    lat:       26.433345,
    lng:       127.808541,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "Cafe Ajyute（カフェアジュテ）",
    genre:     "カフェ・パン",
    address:   "沖縄県うるま市石川2140-5",
    hours:     "月〜金 10:00〜16:00（L.O. 15:30）\n※パン売り切れ次第終了",
    closed:    "土・日・祝日",
    note:      "就労継続支援施設が運営。焼きたてパン食べ放題（1時間 1,000円・ドリンク込み）",
    note_en:   "Run by a welfare support facility. All-you-can-eat freshly baked bread (1 hr / ¥1,000 incl. drink).",
    sourceUrl: "https://ajyute.com/cafe-ajyute/",
    warn:      false,
    lat:       26.416168,
    lng:       127.832946,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "https://ajyute.com/cafe-ajyute/",
    detailText: "",
    photos:     []
  },
  {
    name:      "喜食てんてん",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川山城1706-6",
    hours:     "ランチ 11:00〜13:30\n居酒屋 18:00〜24:00",
    closed:    "日曜日",
    note:      "チキンカツ定食が名物（もも肉1.5枚分のボリューム）。地元の人気食堂",
    note_en:   "Famous for the generous chicken katsu set (1.5 thigh portions). A popular local diner.",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47013479/",
    warn:      false,
    lat:       26.412381,
    lng:       127.820619,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "居酒屋パラダイス",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川2丁目39-15",
    hours:     "ランチ 11:30〜15:00\n居酒屋 18:00〜24:00",
    closed:    "要確認（月・木、または水・第5日曜という情報あり）",
    note:      "ランチの骨汁・カツチャーハンが名物。地元客に人気",
    note_en:   "Lunch specialties: bone soup (骨汁) & katsu fried rice. Popular with locals.",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47007823/",
    warn:      true,
    lat:       26.427576,
    lng:       127.821275,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },

  // ── 追加10店舗（2026-05-08） ─────────────────────────────────────
  {
    name:      "まるみつ食堂",
    genre:     "食事処",
    address:   "沖縄県うるま市石川東山1丁目22-11",
    hours:     "10:30〜14:30頃（売り切れ次第終了）",
    closed:    "水曜日（年末年始・旧盆休あり）",
    note:      "1949年創業の老舗。てびちそば・三枚肉そばが名物。地元民に愛され続ける昭和の食堂",
    note_en:   "Founded in 1949. Famous for tebichi soba & sanmainiku soba. A beloved Showa-era diner.",
    sourceUrl: "https://ryukyu-entertainment.com/marumitu/",
    warn:      false,
    lat:       26.4347222,
    lng:       127.8380556,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "和カフェ Agariyama（アガリヤマ）",
    genre:     "カフェ・八重山そば",
    address:   "沖縄県うるま市石川東山1-8-3",
    hours:     "水〜金 10:00〜15:00 / 17:00〜22:00\n土 10:00〜22:00 / 日 10:00〜19:00",
    closed:    "月・火曜日",
    note:      "2024年5月オープン。石垣島出身オーナーのログハウス風隠れ家カフェ。八重山そばも提供",
    note_en:   "Opened May 2024. Hidden log-cabin café by an owner from Ishigaki Island. Also serves Yaeyama soba.",
    sourceUrl: "https://omalblog.com/2024/12/08/uruma-gariyama/",
    warn:      false,
    lat:       26.4373232,
    lng:       127.8354213,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "大衆酒場 照らす家 石川店",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川白浜1丁目3-5",
    hours:     "〜翌3:00（詳細は要確認）",
    closed:    "要確認",
    note:      "セルフスタイルの飲み放題（990円〜）が人気。訪問前に営業時間を確認推奨",
    note_en:   "Popular self-serve all-you-can-drink (from ¥990). Check hours before visiting.",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47033173/",
    warn:      false,
    lat:       26.427654,
    lng:       127.8269779,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "榮料理店（さかえりょうりてん）",
    genre:     "食事処",
    address:   "沖縄県うるま市石川伊波1553-463",
    hours:     "18:00〜21:30",
    closed:    "日曜日・不定休",
    note:      "予約必須の本格沖縄料理店。コース料理のみ。地元・米軍関係者にも人気の名店",
    note_en:   "Reservation required. Course menu only. Popular with locals and US military personnel.",
    sourceUrl: "http://niraicuisine.com/",
    warn:      false,
    lat:       26.4341514,
    lng:       127.8112099,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "http://niraicuisine.com/",
    detailText: "",
    photos:     []
  },
  {
    name:      "パーラー K's Pit（ケーズピット）",
    genre:     "食事処",
    address:   "沖縄県うるま市石川曙1丁目2-17",
    hours:     "11:00〜18:00（L.O. 17:00）\n※18時以降は予約営業",
    closed:    "不定休",
    note:      "2022年オープン。本格アメリカンバーガー専門店。屋上にオーシャンビューテラス席あり",
    note_en:   "Opened 2022. Authentic American-style burger shop. Rooftop ocean-view terrace available.",
    sourceUrl: "https://www.otv.co.jp/okitive/article/23464/",
    warn:      false,
    lat:       26.421304,
    lng:       127.826424,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "たらの芽",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川白浜2丁目3-2",
    hours:     "ランチ 12:00〜14:00\n夜 17:30〜翌1:00",
    closed:    "日曜日",
    note:      "地元民に愛される老舗の和食居酒屋。刺身定食・天ぷらが名物",
    note_en:   "Long-established Japanese izakaya loved by locals. Known for sashimi set & tempura.",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47006947/",
    warn:      false,
    lat:       26.4272451,
    lng:       127.8270008,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "石川 柿兵衛（かきべえ）",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川1丁目14-2",
    hours:     "17:00〜翌2:00",
    closed:    "なし（年中無休）",
    note:      "備長炭で焼く本格焼き鳥居酒屋。飲み放題コースあり",
    note_en:   "Authentic yakitori izakaya using binchotan charcoal. All-you-can-drink courses available.",
    sourceUrl: "https://www.hotpepper.jp/strJ001017977/",
    warn:      false,
    lat:       26.4298734,
    lng:       127.822802,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "麺や KEIJIRO 石川店",
    genre:     "ラーメン",
    address:   "沖縄県うるま市石川1丁目28-19",
    hours:     "11:00〜16:00 / 18:00〜翌4:00",
    closed:    "不定休（月・金の昼営業なし）",
    note:      "石川店限定の濃厚鶏白湯スープが特徴。深夜4時まで営業",
    note_en:   "Exclusive rich chicken paitan (white broth) soup at the Ishikawa branch. Open until 4am.",
    sourceUrl: "https://www.otv.co.jp/okitive/article/95697/",
    warn:      false,
    lat:       26.4303538,
    lng:       127.8286398,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "石川の駅",
    genre:     "食事処",
    address:   "沖縄県うるま市石川赤崎2丁目2-1",
    hours:     "10:00〜20:00頃（要確認）",
    closed:    "要確認",
    note:      "ホームセンタータバタ石川店内の食堂。ステーキ定食・沖縄そばなどメニュー豊富",
    note_en:   "Diner inside Tabata Home Center Ishikawa. Wide menu: steak set, Okinawa soba & more.",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47011395/",
    warn:      false,
    lat:       26.4342224,
    lng:       127.8353657,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    name:      "酒処 金の蔵（きんのくら）",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川1丁目28-9",
    hours:     "ランチ 11:00〜15:00\n夜 18:00〜24:00",
    closed:    "要確認",
    note:      "同じ建物に姉妹店「キンクラバーガー」あり",
    note_en:   "Sister restaurant 'Kinkura Burger' is located in the same building.",
    sourceUrl: "https://r.goope.jp/kinnokura/",
    warn:      false,
    lat:       26.430094,
    lng:       127.828385,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "https://r.goope.jp/kinnokura/",
    detailText: "",
    photos:     []
  },

  // ── コンビニエンスストア ──────────────────────────────────────────
  {
    name:      "ローソン うるま石川店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川2-24-9",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・コピー機あり",
    note_en:   "ATM and copy machine available.",
    sourceUrl: "https://store.lawson.co.jp/",
    warn:      false,
    lat:       26.42517,
    lng:       127.82526,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },
  {
    name:      "ファミリーマート 石川一丁目店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川1-27-41",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・イートインスペースあり",
    note_en:   "ATM and eat-in space available.",
    sourceUrl: "https://www.family.co.jp/",
    warn:      false,
    lat:       26.428554,
    lng:       127.827190,
    twitter: "", instagram: "", youtube: "", website: "https://www.family.co.jp/", detailText: "", photos: []
  },
  {
    name:      "セブンイレブン 石川インター店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川2337",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・コピー機あり",
    note_en:   "ATM and copy machine available.",
    sourceUrl: "https://www.sej.co.jp/",
    warn:      false,
    lat:       26.434586,
    lng:       127.826263,
    twitter: "", instagram: "", youtube: "", website: "https://www.sej.co.jp/", detailText: "", photos: []
  },

  // ── ガソリンスタンド ──────────────────────────────────────────────
  {
    name:      "ENEOSサンセール石川インターSS",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川2337",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "石川インター近く。株式会社山城石油が運営",
    note_en:   "Near Ishikawa interchange. Operated by Yamashiro Oil.",
    sourceUrl: "https://navitime.co.jp/",
    warn:      false,
    lat:       26.434555,
    lng:       127.826689,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    name:      "伊波SS（神谷石油）",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川伊波309",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://navitime.co.jp/",
    warn:      true,
    lat:       26.414359,
    lng:       127.823418,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    name:      "嘉手苅SS（くだか石油）",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川嘉手苅141-6",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://navitime.co.jp/",
    warn:      true,
    lat:       26.420632,
    lng:       127.813352,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },

  // ── テスト用店舗（石川ビーチ沖合・動作確認専用） ─────────────────
  {
    name:      "【テスト】石川ビーチ海上店",
    genre:     "テスト用",
    address:   "石川ビーチ沖合（テスト用・実在しません）",
    hours:     "テスト営業時間 9:00〜18:00",
    closed:    "テスト定休日",
    note:      "これは動作確認用のテスト店舗です。実在しません。店舗オーナー操作機能の確認に使用します。",
    note_en:   "This is a test store for system verification. Not a real restaurant.",
    sourceUrl: "",
    warn:      false,
    alwaysShow: true,
    lat:       26.4268,
    lng:       127.8415,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "これはテスト用の店舗です。\n\n今後、店舗オーナーが自分で情報を更新・追加できる機能の確認に使用します。\n\n実際の営業はしていません。",
    photos:     []
  },
  // ── 宿泊施設 ───────────────────────────────────────────────────
  {
    name:      "ココ ガーデンリゾート オキナワ",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川伊波501",
    hours:     "チェックイン 15:00〜 / チェックアウト 〜11:00",
    closed:    "年中無休",
    note:      "石川海岸沿いのリゾートホテル",
    sourceUrl: "https://cocogarden.com/",
    warn:      false,
    lat:       26.42030,
    lng:       127.81988
  },
  {
    name:      "アンサ沖縄リゾート",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川山城1468",
    hours:     "チェックイン 15:00〜 / チェックアウト 〜11:00",
    closed:    "年中無休",
    note:      "石川エリアのリゾートホテル",
    sourceUrl: "https://www.city.uruma.lg.jp/sportscamp/21522/index.html",
    warn:      false,
    lat:       26.41774,
    lng:       127.79255
  },
  {
    name:      "民宿レキオ",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川2-26-4",
    hours:     "チェックイン 16:00〜 / チェックアウト 〜10:00",
    closed:    "要確認",
    note:      "石川エリアの民宿",
    sourceUrl: "http://www.lequio7.sakura.ne.jp/",
    warn:      false,
    lat:       26.42586,
    lng:       127.82483
  },
  {
    name:      "民宿やすま",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川曙2丁目3-1",
    hours:     "チェックイン 16:00〜 / チェックアウト 〜10:00",
    closed:    "要確認",
    note:      "石川エリアの民宿",
    sourceUrl: "https://uruma-ru.jp/stay/",
    warn:      false,
    lat:       26.42059,
    lng:       127.82524
  },
  // ── 金融機関 ───────────────────────────────────────────────────
  {
    name:      "琉球銀行 石川支店",
    genre:     "金融",
    address:   "沖縄県うるま市石川2-23-6",
    hours:     "平日 9:00〜15:00",
    closed:    "土・日・祝日",
    note:      "ATMは時間外も利用可",
    sourceUrl: "https://www.ryugin.co.jp/tenpo/atm_search/shop-5030/",
    warn:      false,
    lat:       26.42626,
    lng:       127.82578
  },
  {
    name:      "沖縄銀行 石川支店",
    genre:     "金融",
    address:   "沖縄県うるま市石川2丁目24-1",
    hours:     "平日 9:00〜15:00",
    closed:    "土・日・祝日",
    note:      "ATMは時間外も利用可",
    sourceUrl: "https://gincode.com/branch_0188_315",
    warn:      false,
    lat:       26.42580,
    lng:       127.82557
  },
  {
    name:      "石川郵便局",
    genre:     "金融",
    address:   "沖縄県うるま市石川東山本町1-1-2",
    hours:     "郵便 平日9:00〜17:00 / 貯金 平日9:00〜16:00",
    closed:    "土・日・祝日",
    note:      "ATMあり（土日も利用可）",
    sourceUrl: "https://map.japanpost.jp/p/search/dtl/300170031000/",
    warn:      false,
    lat:       26.43363,
    lng:       127.83207
  },
  // ── 教育施設 ───────────────────────────────────────────────────
  {
    name:      "うるま市立宮森小学校",
    genre:     "教育",
    address:   "沖縄県うるま市石川1丁目46-1",
    hours:     "平日 8:00〜17:00（登校日）",
    closed:    "土・日・祝日・長期休暇",
    note:      "",
    sourceUrl: "https://www.city.uruma.lg.jp/",
    warn:      false,
    lat:       26.43175,
    lng:       127.82759
  },
  {
    name:      "うるま市立石川中学校",
    genre:     "教育",
    address:   "沖縄県うるま市石川440番地1",
    hours:     "平日 8:00〜17:00（登校日）",
    closed:    "土・日・祝日・長期休暇",
    note:      "",
    sourceUrl: "https://j-ishikawa.edu.city.uruma.okinawa.jp/",
    warn:      false,
    lat:       26.42399,
    lng:       127.82429
  },
  {
    name:      "沖縄県立石川高等学校",
    genre:     "教育",
    address:   "沖縄県うるま市石川伊波861",
    hours:     "平日 8:00〜17:00（登校日）",
    closed:    "土・日・祝日・長期休暇",
    note:      "普通科",
    sourceUrl: "https://www.ishikawa-h.open.ed.jp/",
    warn:      false,
    lat:       26.41535,
    lng:       127.82052
  },
  // ── 観光スポット ───────────────────────────────────────────────
  {
    name:      "石川ビーチ（石川公園）",
    genre:     "観光",
    address:   "沖縄県うるま市石川曙",
    hours:     "年中無休（自由）",
    closed:    "なし",
    note:      "ウィンドサーフィンで有名な市民ビーチ。リーフ内は砂地で安全",
    sourceUrl: "https://www.okinawastory.jp/spot/600006184",
    warn:      false,
    lat:       26.42574,
    lng:       127.82849
  },
  {
    name:      "石川岳（市民の森公園）",
    genre:     "観光",
    address:   "沖縄県うるま市石川",
    hours:     "年中無休（自由）",
    closed:    "なし",
    note:      "標高204m。山頂展望台から太平洋と東シナ海を一望できる",
    sourceUrl: "https://www.city.uruma.lg.jp/miryoku/p000001.html",
    warn:      false,
    lat:       26.44810,
    lng:       127.83208
  }
];
