// ── 店舗データ ─────────────────────────────────────────────────
// detail.html と script.js の両方から読み込む共通データファイル
const restaurants = [
  {
    id:          0,
    code:        "47213-IS-0001",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "酒楽場うまし家",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川1丁目28-18",
    hours:     "17:00〜翌1:00",
    closed:    "火曜日",
    note:      "創業40年超。石川社交街の老舗大衆居酒屋。県産無農薬野菜使用",
    note_en:   "Over 40 years in business. A long-established izakaya in Ishikawa's entertainment district. Uses locally grown organic vegetables.",
    sourceUrl: "https://umashiya.com/about/",
    sourceUrls: ["https://umashiya.com/about/", "https://www.ekiten.jp/shop_2457951/", "https://map.yahoo.co.jp/v3/place/X0m4ICbJzsI"],
    warn:      false,
    lat:       26.430443,
    lng:       127.828701,
    // 詳細ページ用フィールド
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "https://umashiya.com/",
    detailText: "",
    photos:     []
  },
  {
    id:          1,
    code:        "47213-IS-0002",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "クリームソーダ",
    genre:     "バル（中華・和食・バー）",
    address:   "沖縄県うるま市石川白浜1-2-1 2F",
    hours:     "中華ランチ：月・木・金 11:30〜14:00\nBAR：年中無休 18:00〜\n中華ディナー：土・日 18:00〜21:00",
    closed:    "不定休",
    note:      "営業スタイルが複雑。訪問前に公式サイトで要確認",
    note_en:   "Complex schedule. Please check the official site before visiting.",
    sourceUrl: "https://balcreamsoda.com/",
    sourceUrls: ["https://balcreamsoda.com/", "https://okinawaly.com/living/post-1103/"],
    warn:      false,
    lat:       26.427302,
    lng:       127.827541,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "https://balcreamsoda.com/",
    detailText: "",
    photos:     []
  },
  {
    id:          2,
    code:        "47213-IS-0003",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "杏屋 石川店",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川白浜1-4-7",
    hours:     "18:00〜翌3:00（料理L.O. 翌1:45）",
    closed:    "なし（年中無休）",
    note:      "深夜営業。個室あり。飲み放題コースあり",
    note_en:   "Late-night hours. Private rooms available. All-you-can-drink courses offered.",
    sourceUrl: "https://www.hotpepper.jp/strJ001017974/",
    sourceUrls: ["https://www.hotpepper.jp/strJ001017974/", "https://map.yahoo.co.jp/v3/place/pSf9Gj702gc"],
    warn:      false,
    lat:       26.428326,
    lng:       127.827701,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          3,
    code:        "47213-IS-0004",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "牛角 うるま石川店",
    genre:     "焼肉",
    address:   "沖縄県うるま市石川1-16-18",
    hours:     "16:00〜23:00",
    closed:    "年中無休",
    note:      "チェーン店（牛角グループ）",
    note_en:   "Chain restaurant (Gyukaku group).",
    sourceUrl: "https://map.reins.co.jp/gyukaku/detail/989653529",
    sourceUrls: ["https://map.reins.co.jp/gyukaku/detail/989653529", "https://r.gnavi.co.jp/420y0ukw0000/"],
    warn:      false,
    lat:       26.431203,
    lng:       127.825063,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          4,
    code:        "47213-IS-0005",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "Capful（キャプフル）",
    genre:     "カフェ",
    address:   "沖縄県うるま市石川曙1丁目6-1",
    hours:     "7:30〜15:30（月〜木）\n7:30〜21:00（金・土・日）",
    closed:    "水曜日",
    note:      "元外国人住宅を改装。海が見えるテラス席。朝食営業あり",
    note_en:   "Renovated former US military housing. Terrace seating with ocean view. Breakfast available.",
    sourceUrl: "https://www.instagram.com/okinawa_capful/",
    sourceUrls: ["https://www.instagram.com/okinawa_capful/", "https://okinawatravel.jp/capful"],
    warn:      false,
    lat:       26.420088,
    lng:       127.828450,
    twitter:    "",
    instagram:  "https://www.instagram.com/okinawa_capful/",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          5,
    code:        "47213-IS-0006",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "HINA CAFE（ヒナカフェ）",
    genre:     "カフェ・イタリアン",
    address:   "沖縄県うるま市石川白浜1-1-1 2F",
    hours:     "ランチ 11:30〜15:30\nディナー（金〜日）16:00〜22:00",
    closed:    "月〜水曜日",
    note:      "2023年6月オープン。本格イタリアン",
    note_en:   "Opened June 2023. Authentic Italian cuisine.",
    sourceUrl: "https://hitosara.com/0004038163/",
    sourceUrls: ["https://hitosara.com/0004038163/", "https://tabelog.com/en/okinawa/A4703/A470302/47030276/"],
    warn:      false,
    lat:       26.427231,
    lng:       127.827883,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          6,
    code:        "47213-IS-0007",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "GENCO（ジェンコ）",
    genre:     "カフェ・バー（ハワイ料理）",
    address:   "沖縄県うるま市石川伊波1515-32",
    hours:     "11:11〜15:00 / 17:00〜23:00",
    closed:    "火曜日",
    note:      "食べログに営業状況「未確認」の記載あり。訪問前に電話確認を推奨（098-988-5863）",
    note_en:   "Listed as 'unconfirmed' on Tabelog. Recommended to call ahead before visiting (098-988-5863).",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47031510/",
    sourceUrls: ["https://tabelog.com/okinawa/A4703/A470302/47031510/", "https://ryukyushimpo.jp/style/gourmet/entry-2823371.html"],
    warn:      true,
    lat:       26.433345,
    lng:       127.808541,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          7,
    code:        "47213-IS-0008",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "Cafe Ajyute（カフェアジュテ）",
    genre:     "カフェ・パン",
    address:   "沖縄県うるま市石川2140-5",
    hours:     "月〜金 10:00〜16:00（L.O. 15:30）\n※パン売り切れ次第終了",
    closed:    "土・日・祝日",
    note:      "就労継続支援施設が運営。焼きたてパン食べ放題（1時間 1,000円・ドリンク込み）",
    note_en:   "Run by a welfare support facility. All-you-can-eat freshly baked bread (1 hr / ¥1,000 incl. drink).",
    sourceUrl: "https://ajyute.com/cafe-ajyute/",
    sourceUrls: ["https://ajyute.com/cafe-ajyute/", "https://map.yahoo.co.jp/v3/place/LL8lCh1uXAE"],
    warn:      false,
    lat:       26.416168,
    lng:       127.832946,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "https://ajyute.com/cafe-ajyute/",
    detailText: "",
    photos:     []
  },
  {
    id:          8,
    code:        "47213-IS-0009",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "喜食てんてん",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川山城1706-6",
    hours:     "ランチ 11:00〜13:30\n居酒屋 18:00〜24:00",
    closed:    "日曜日",
    note:      "チキンカツ定食が名物（もも肉1.5枚分のボリューム）。地元の人気食堂",
    note_en:   "Famous for the generous chicken katsu set (1.5 thigh portions). A popular local diner.",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47013479/",
    sourceUrls: ["https://tabelog.com/okinawa/A4703/A470302/47013479/", "https://www.ekiten.jp/shop_71083176/"],
    warn:      false,
    lat:       26.412381,
    lng:       127.820619,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          9,
    code:        "47213-IS-0010",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "居酒屋パラダイス",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川2丁目39-15",
    hours:     "ランチ 11:30〜15:00\n居酒屋 18:00〜24:00",
    closed:    "要確認（月・木、または水・第5日曜という情報あり）",
    note:      "ランチの骨汁・カツチャーハンが名物。地元客に人気",
    note_en:   "Lunch specialties: bone soup (骨汁) & katsu fried rice. Popular with locals.",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47007823/",
    sourceUrls: ["https://tabelog.com/okinawa/A4703/A470302/47007823/", "https://www.ekiten.jp/shop_7136480/", "https://hitosara.com/0031479619/"],
    warn:      true,
    lat:       26.427576,
    lng:       127.821275,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },

  // ── 追加10店舗（2026-05-08） ─────────────────────────────────────
  {
    id:          10,
    code:        "47213-IS-0011",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "まるみつ食堂",
    genre:     "食事処",
    address:   "沖縄県うるま市石川東山1丁目22-11",
    hours:     "10:30〜14:30頃（売り切れ次第終了）",
    closed:    "水曜日（年末年始・旧盆休あり）",
    note:      "1949年創業の老舗。てびちそば・三枚肉そばが名物。地元民に愛され続ける昭和の食堂",
    note_en:   "Founded in 1949. Famous for tebichi soba & sanmainiku soba. A beloved Showa-era diner.",
    sourceUrl: "https://ryukyu-entertainment.com/marumitu/",
    sourceUrls: ["https://ryukyu-entertainment.com/marumitu/", "https://retty.me/area/PRE47/ARE267/SUB26705/100001211041/"],
    warn:      false,
    lat:       26.4347222,
    lng:       127.8380556,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          11,
    code:        "47213-IS-0012",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "和カフェ Agariyama（アガリヤマ）",
    genre:     "カフェ・八重山そば",
    address:   "沖縄県うるま市石川東山1-8-3",
    hours:     "水〜金 10:00〜15:00 / 17:00〜22:00\n土 10:00〜22:00 / 日 10:00〜19:00",
    closed:    "月・火曜日",
    note:      "2024年5月オープン。石垣島出身オーナーのログハウス風隠れ家カフェ。八重山そばも提供",
    note_en:   "Opened May 2024. Hidden log-cabin café by an owner from Ishigaki Island. Also serves Yaeyama soba.",
    sourceUrl: "https://omalblog.com/2024/12/08/uruma-gariyama/",
    sourceUrls: ["https://omalblog.com/2024/12/08/uruma-gariyama/", "https://map.yahoo.co.jp/v3/place/rX-1n8b3hFo"],
    warn:      false,
    lat:       26.4373232,
    lng:       127.8354213,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          12,
    code:        "47213-IS-0013",
    status:      "published",
    tel:         "",
    lastChecked: "2026-07-29",
    name:      "大衆酒場 照らす家 石川店",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川白浜1丁目3-5",
    hours:     "17:00〜翌3:00",
    closed:    "要確認",
    note:      "セルフスタイルの飲み放題（990円〜）が人気。訪問前に営業時間を確認推奨",
    note_en:   "Popular self-serve all-you-can-drink (from ¥990). Check hours before visiting.",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47033173/",
    sourceUrls: ["https://tabelog.com/okinawa/A4703/A470302/47033173/", "https://hitosara.com/0031728796/"],
    warn:      true,
    lat:       26.427654,
    lng:       127.8269779,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          13,
    code:        "47213-IS-0014",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "榮料理店（さかえりょうりてん）",
    genre:     "食事処",
    address:   "沖縄県うるま市石川伊波1553-463",
    hours:     "18:00〜21:30",
    closed:    "日曜日・不定休",
    note:      "予約必須の本格沖縄料理店。コース料理のみ。地元・米軍関係者にも人気の名店",
    note_en:   "Reservation required. Course menu only. Popular with locals and US military personnel.",
    sourceUrl: "http://niraicuisine.com/",
    sourceUrls: ["http://niraicuisine.com/", "https://paypaygourmet.yahoo.co.jp/124938"],
    warn:      false,
    lat:       26.4341514,
    lng:       127.8112099,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "http://niraicuisine.com/",
    detailText: "",
    photos:     []
  },
  {
    id:          14,
    code:        "47213-IS-0015",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "パーラー K's Pit（ケーズピット）",
    genre:     "食事処",
    address:   "沖縄県うるま市石川曙1丁目2-17",
    hours:     "11:00〜18:00（L.O. 17:00）\n※18時以降は予約営業",
    closed:    "不定休",
    note:      "2022年オープン。本格アメリカンバーガー専門店。屋上にオーシャンビューテラス席あり",
    note_en:   "Opened 2022. Authentic American-style burger shop. Rooftop ocean-view terrace available.",
    sourceUrl: "https://www.otv.co.jp/okitive/article/23464/",
    sourceUrls: ["https://www.otv.co.jp/okitive/article/23464/", "https://map.yahoo.co.jp/v3/place/9Rk9gUCDTcM", "https://tabelog.com/en/okinawa/A4703/A470302/47029035/"],
    warn:      false,
    lat:       26.421304,
    lng:       127.826424,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          15,
    code:        "47213-IS-0016",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "たらの芽",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川白浜2丁目3-2",
    hours:     "ランチ 12:00〜14:00\n夜 17:30〜翌1:00",
    closed:    "日曜日",
    note:      "地元民に愛される老舗の和食居酒屋。刺身定食・天ぷらが名物",
    note_en:   "Long-established Japanese izakaya loved by locals. Known for sashimi set & tempura.",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47006947/",
    sourceUrls: ["https://tabelog.com/okinawa/A4703/A470302/47006947/", "https://map.yahoo.co.jp/v3/place/4fz4CWfNo66", "https://okinawa-tabearuki.com/archives/666"],
    warn:      false,
    lat:       26.4272451,
    lng:       127.8270008,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          16,
    code:        "47213-IS-0017",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "石川 柿兵衛（かきべえ）",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川1丁目14-2",
    hours:     "17:00〜翌2:00",
    closed:    "なし（年中無休）",
    note:      "備長炭で焼く本格焼き鳥居酒屋。飲み放題コースあり",
    note_en:   "Authentic yakitori izakaya using binchotan charcoal. All-you-can-drink courses available.",
    sourceUrl: "https://www.hotpepper.jp/strJ001017977/",
    sourceUrls: ["https://www.hotpepper.jp/strJ001017977/", "https://retty.me/area/PRE47/ARE267/SUB26705/100001152816/"],
    warn:      false,
    lat:       26.4298734,
    lng:       127.822802,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          17,
    code:        "47213-IS-0018",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "麺や KEIJIRO 石川店",
    genre:     "ラーメン",
    address:   "沖縄県うるま市石川1丁目28-19",
    hours:     "11:00〜16:00 / 18:00〜翌4:00",
    closed:    "不定休（月・金の昼営業なし）",
    note:      "石川店限定の濃厚鶏白湯スープが特徴。深夜4時まで営業",
    note_en:   "Exclusive rich chicken paitan (white broth) soup at the Ishikawa branch. Open until 4am.",
    sourceUrl: "https://www.otv.co.jp/okitive/article/95697/",
    sourceUrls: ["https://www.otv.co.jp/okitive/article/95697/", "https://retty.me/area/PRE47/ARE267/SUB26705/100001577229/", "https://map.yahoo.co.jp/v3/place/zJvRtaWsHsg"],
    warn:      false,
    lat:       26.4303538,
    lng:       127.8286398,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          18,
    code:        "47213-IS-0019",
    status:      "published",
    tel:         "",
    lastChecked: "2026-07-29",
    name:      "石川の駅",
    genre:     "食事処",
    address:   "沖縄県うるま市石川赤崎2丁目2-1",
    hours:     "10:00〜20:30",
    closed:    "年中無休(お盆・1月1日のみ休み)",
    note:      "ホームセンタータバタ石川店内の食堂。ステーキ定食・沖縄そばなどメニュー豊富",
    note_en:   "Diner inside Tabata Home Center Ishikawa. Wide menu: steak set, Okinawa soba & more.",
    sourceUrl: "https://tabelog.com/okinawa/A4703/A470302/47011395/",
    sourceUrls: ["https://tabelog.com/okinawa/A4703/A470302/47011395/", "https://map.yahoo.co.jp/v3/place/HTcEb_rP_d6", "https://retty.me/area/PRE47/ARE267/SUB26705/100001045603/"],
    warn:      false,
    lat:       26.4342224,
    lng:       127.8353657,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "",
    photos:     []
  },
  {
    id:          19,
    code:        "47213-IS-0020",
    status:      "published",
    tel:         "",
    lastChecked: "2026-07-29",
    name:      "酒処 金の蔵（きんのくら）",
    genre:     "居酒屋等",
    address:   "沖縄県うるま市石川1丁目28-9",
    hours:     "ランチ 11:00〜15:00\n夜 18:00〜24:00",
    closed:    "月曜日・日曜日",
    note:      "同じ建物に姉妹店「キンクラバーガー」あり",
    note_en:   "Sister restaurant 'Kinkura Burger' is located in the same building.",
    sourceUrl: "https://www.facebook.com/Sakedokorokinnokura/",
    sourceUrls: ["https://www.facebook.com/Sakedokorokinnokura/", "https://r.goope.jp/kinnokura/about"],
    warn:      false,
    lat:       26.430094,
    lng:       127.828385,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "https://r.goope.jp/kinnokura/",
    detailText: "",
    photos:     []
  },

  // ── コンビニエンスストア ──────────────────────────────────────────
  {
    id:          20,
    code:        "47213-IS-0021",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ローソン うるま石川店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川2-24-9",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・コピー機あり",
    note_en:   "ATM and copy machine available.",
    sourceUrl: "https://store.lawson.co.jp/",
    sourceUrls: ["https://store.lawson.co.jp/", "https://www.mapion.co.jp/phonebook/M02005/47213/ILSP0000504812_ipclm/"],
    warn:      false,
    lat:       26.42517,
    lng:       127.82526,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },
  {
    id:          21,
    code:        "47213-IS-0022",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ファミリーマート 石川一丁目店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川1-27-41",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・イートインスペースあり",
    note_en:   "ATM and eat-in space available.",
    sourceUrl: "https://www.family.co.jp/",
    sourceUrls: ["https://www.family.co.jp/", "https://store.family.co.jp/points/72085"],
    warn:      false,
    lat:       26.428554,
    lng:       127.827190,
    twitter: "", instagram: "", youtube: "", website: "https://www.family.co.jp/", detailText: "", photos: []
  },
  {
    id:          22,
    code:        "47213-IS-0023",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "セブンイレブン 石川インター店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川2337",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・コピー機あり",
    note_en:   "ATM and copy machine available.",
    sourceUrl: "https://www.sej.co.jp/",
    sourceUrls: ["https://www.sej.co.jp/", "https://map.yahoo.co.jp/v3/place/qUlcR4hcJro"],
    warn:      false,
    lat:       26.434586,
    lng:       127.826263,
    twitter: "", instagram: "", youtube: "", website: "https://www.sej.co.jp/", detailText: "", photos: []
  },
  // ※以下4件のファミマ＋3件のローソンは2026-07-21にOpenStreetMap抽出＋
  //   公式店舗検索等とのウェブ二重照合で追加（座標はOSM、住所・店名は公式等で確認）
  {
    id:          23,
    code:        "47213-IS-0024",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ファミリーマート 石川東山店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川東山1-22-11",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://store.family.co.jp/points/07258",
    warn:      false,
    lat:       26.434764,
    lng:       127.838129,
    twitter: "", instagram: "", youtube: "", website: "https://www.family.co.jp/", detailText: "", photos: []
  },
  {
    id:          24,
    code:        "47213-IS-0025",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ファミリーマート 石川白浜店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川白浜2-8-26",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・駐車場あり",
    note_en:   "ATM and parking available.",
    sourceUrl: "https://www.family.co.jp/",
    sourceUrls: ["https://www.family.co.jp/", "https://www.homemate-research-convenience-store.com/dtl/00000000000000551354/"],
    warn:      false,
    lat:       26.424311,
    lng:       127.825500,
    twitter: "", instagram: "", youtube: "", website: "https://www.family.co.jp/", detailText: "", photos: []
  },
  {
    id:          25,
    code:        "47213-IS-0026",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ファミリーマート 石川高校前店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川伊波294-1",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.family.co.jp/",
    sourceUrls: ["https://www.family.co.jp/", "https://www.navitime.co.jp/poi?spot=01155-ofm00000131"],
    warn:      false,
    lat:       26.415741,
    lng:       127.821848,
    twitter: "", instagram: "", youtube: "", website: "https://www.family.co.jp/", detailText: "", photos: []
  },
  {
    id:          26,
    code:        "47213-IS-0027",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ファミリーマート 石川東恩納店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川東恩納666-1",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "",
    note_en:   "",
    sourceUrl: "https://store.family.co.jp/points/72349",
    sourceUrls: ["https://store.family.co.jp/points/72349", "https://www.navitime.co.jp/poi?spot=01155-ofm00000305"],
    warn:      false,
    lat:       26.410708,
    lng:       127.827042,
    twitter: "", instagram: "", youtube: "", website: "https://www.family.co.jp/", detailText: "", photos: []
  },
  {
    id:          27,
    code:        "47213-IS-0028",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ローソン 石川バイパス店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川山城842-3",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "国道329号石川バイパス沿い・駐車場あり",
    note_en:   "On Route 329 Ishikawa Bypass. Parking available.",
    sourceUrl: "https://www.e-map.ne.jp/p/lawson/dtl/241123/",
    sourceUrls: ["https://www.e-map.ne.jp/p/lawson/dtl/241123/", "https://www.navitime.co.jp/poi?spot=01150-241123"],
    warn:      false,
    lat:       26.412944,
    lng:       127.817921,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },
  {
    id:          28,
    code:        "47213-IS-0029",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ローソン うるま石川東恩納店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川東恩納251-1",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・駐車場あり",
    note_en:   "ATM and parking available.",
    sourceUrl: "https://www.e-map.ne.jp/p/lawson/dtl/374700/",
    sourceUrls: ["https://www.e-map.ne.jp/p/lawson/dtl/374700/", "https://www.navitime.co.jp/poi?spot=01150-374700"],
    warn:      false,
    lat:       26.414672,
    lng:       127.834395,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },
  {
    id:          29,
    code:        "47213-IS-0030",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ローソン うるま伊波店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川伊波1512-15",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATM・駐車場あり",
    note_en:   "ATM and parking available.",
    sourceUrl: "https://www.e-map.ne.jp/p/lawson/dtl/287148/",
    sourceUrls: ["https://www.e-map.ne.jp/p/lawson/dtl/287148/", "https://www.navitime.co.jp/poi?spot=01150-287148"],
    warn:      false,
    lat:       26.426880,
    lng:       127.807813,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },
  // ※以下4件は2026-07-21にサイト管理人の指摘を受けて追加。
  //   OSM未登録だったためチェーン公式店舗検索・複数地図サービスで存在・住所・座標を照合済み
  {
    id:          30,
    code:        "47213-IS-0031",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ローソン 石川インター店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川2313-2",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "駐車場あり",
    note_en:   "Parking available.",
    sourceUrl: "https://www.e-map.ne.jp/p/lawson/dtl/269914/",
    sourceUrls: ["https://www.e-map.ne.jp/p/lawson/dtl/269914/", "https://map.yahoo.co.jp/v3/place/nmE6aFXR3u6"],
    warn:      false,
    lat:       26.435600,
    lng:       127.827321,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },
  {
    id:          31,
    code:        "47213-IS-0032",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "セブンイレブン 石川白浜1丁目店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川白浜1-4-17",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATMあり",
    note_en:   "ATM available.",
    sourceUrl: "https://www.sej.co.jp/",
    sourceUrls: ["https://www.sej.co.jp/", "https://location.sevenbank.co.jp/sevenbank/spot/detail?code=0000032573"],
    warn:      false,
    lat:       26.428954,
    lng:       127.827897,
    twitter: "", instagram: "", youtube: "", website: "https://www.sej.co.jp/", detailText: "", photos: []
  },
  {
    id:          32,
    code:        "47213-IS-0033",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "セブンイレブン 石川曙2丁目店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川曙2丁目1-38",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "ATMあり",
    note_en:   "ATM available.",
    sourceUrl: "https://www.e-map.ne.jp/p/711map/dtl/507526/",
    sourceUrls: ["https://www.e-map.ne.jp/p/711map/dtl/507526/", "https://map.yahoo.co.jp/v3/place/RMuEhynq_dk"],
    warn:      false,
    lat:       26.421245,
    lng:       127.825255,
    twitter: "", instagram: "", youtube: "", website: "https://www.sej.co.jp/", detailText: "", photos: []
  },
  {
    id:          33,
    code:        "47213-IS-0034",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ローソン 石川曙三丁目店",
    genre:     "コンビニ",
    address:   "沖縄県うるま市石川曙3-12-76",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "店内に郵便ポストあり",
    note_en:   "Mailbox inside the store.",
    sourceUrl: "https://www.e-map.ne.jp/p/lawson/dtl/286976/",
    sourceUrls: ["https://www.e-map.ne.jp/p/lawson/dtl/286976/", "https://map.yahoo.co.jp/v3/place/V-u7-SiSiYc"],
    warn:      false,
    lat:       26.415945,
    lng:       127.824158,
    twitter: "", instagram: "", youtube: "", website: "https://store.lawson.co.jp/", detailText: "", photos: []
  },

  // ── ガソリンスタンド ──────────────────────────────────────────────
  {
    id:          34,
    code:        "47213-IS-0035",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ENEOSサンセール石川インターSS",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川2337",
    hours:     "24時間",
    closed:    "年中無休",
    note:      "石川インター近く。株式会社山城石油が運営",
    note_en:   "Near Ishikawa interchange. Operated by Yamashiro Oil.",
    sourceUrl: "https://navitime.co.jp/",
    sourceUrls: ["https://navitime.co.jp/", "https://eneos-ss.com/search/ss/pc/detail.php?SCODE=987654"],
    warn:      false,
    lat:       26.434555,
    lng:       127.826689,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          35,
    code:        "47213-IS-0036",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "伊波SS（神谷石油）",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川伊波309",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://navitime.co.jp/",
    sourceUrls: ["https://navitime.co.jp/", "https://e-nenpi.com/gs/shop/47331/", "https://oki-ss.or.jp/?page_id=167"],
    warn:      true,
    lat:       26.414359,
    lng:       127.823418,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          36,
    code:        "47213-IS-0037",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "嘉手苅SS（くだか石油）",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川嘉手苅141-6",
    hours:     "要確認",
    closed:    "要確認",
    note:      "カーエネクス系列。電話098-965-5565（営業時間・定休日は要確認）",
    note_en:   "Carenex brand station. Tel 098-965-5565 (please confirm hours and holidays before visiting).",
    sourceUrl: "https://oki-ss.or.jp/?page_id=167",
    sourceUrls: ["https://oki-ss.or.jp/?page_id=167", "https://e-nenpi.com/gs/shop/47141/", "https://gasoline-gift.zensekiren.or.jp/station/4700007001"],
    warn:      true,
    lat:       26.420632,
    lng:       127.813352,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  // ※以下2件は2026-07-24にOSM抽出＋出光公式SS検索/Yahoo!地図/geocoding.jp等との
  // ウェブ複数照合で追加（poi-surveyスキル手順）
  {
    id:          37,
    code:        "47213-IS-0038",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "アポロステーション石川SS（石川サービス）",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川431",
    hours:     "7:00〜20:00",
    closed:    "年中無休",
    note:      "出光系列アポロステーション。セルフ式。電話098-964-2025",
    note_en:   "Idemitsu apollostation brand, self-service. Tel 098-964-2025.",
    sourceUrl: "https://map.idemitsu.com/b/a/info/0000019740/",
    sourceUrls: ["https://map.idemitsu.com/b/a/info/0000019740/", "https://e-nenpi.com/gs/map/47033", "https://oki-ss.or.jp/?page_id=167"],
    warn:      false,
    lat:       26.424717,
    lng:       127.825160,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          38,
    code:        "47213-IS-0039",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "赤崎サービスステーション（瑞穂石油）",
    genre:     "ガソリン",
    address:   "沖縄県うるま市石川東山本町2-4-1",
    hours:     "7:00〜21:00",
    closed:    "年中無休",
    note:      "カーエネクス系列。フルサービス（洗車・オイル交換等対応）。電話098-964-2626",
    note_en:   "Carenex brand, full-service (car wash, oil change, etc.). Tel 098-964-2626.",
    sourceUrl: "https://map.yahoo.co.jp/v3/place/5mvXtr9ABzU",
    sourceUrls: ["https://map.yahoo.co.jp/v3/place/5mvXtr9ABzU", "https://e-nenpi.com/gs/shop/47016/", "https://oki-ss.or.jp/?page_id=167"],
    warn:      false,
    lat:       26.434840,
    lng:       127.835272,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },

  // ── テスト用店舗（石川ビーチ沖合・動作確認専用） ─────────────────
  {
    id:          39,
    code:        "47213-IS-0040",
    status:      "test",
    tel:         "",
    lastChecked: "",
    name:      "【テスト】石川ビーチ海上店",
    genre:     "テスト用",
    address:   "石川ビーチ沖合（テスト用・実在しません）",
    hours:     "テスト営業時間 9:00〜18:00",
    closed:    "テスト定休日",
    note:      "これは動作確認用のテスト店舗です。実在しません。店舗オーナー操作機能の確認に使用します。",
    note_en:   "This is a test store for system verification. Not a real restaurant.",
    sourceUrl: "",
    warn:      false,
    alwaysShow: true,
    lat:       26.4268,
    lng:       127.8415,
    twitter:    "",
    instagram:  "",
    youtube:    "",
    website:    "",
    detailText: "これはテスト用の店舗です。\n\n今後、店舗オーナーが自分で情報を更新・追加できる機能の確認に使用します。\n\n実際の営業はしていません。",
    photos:     []
  },
  // ── 宿泊施設 ───────────────────────────────────────────────────
  {
    id:          40,
    code:        "47213-IS-0041",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ココ ガーデンリゾート オキナワ",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川伊波501",
    hours:     "チェックイン 15:00〜 / チェックアウト 〜11:00",
    closed:    "年中無休",
    note:      "石川海岸沿いのリゾートホテル",
    sourceUrl: "https://cocogarden.com/",
    sourceUrls: ["https://cocogarden.com/", "https://www.jalan.net/yad339494/", "https://www.okinawastory.jp/stay/1241"],
    warn:      false,
    lat:       26.42030,
    lng:       127.81988
  },
  {
    id:          41,
    code:        "47213-IS-0042",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "アンサ沖縄リゾート",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川山城1468",
    hours:     "チェックイン 15:00〜 / チェックアウト 〜11:00",
    closed:    "年中無休",
    note:      "石川エリアのリゾートホテル",
    sourceUrl: "https://www.city.uruma.lg.jp/sportscamp/21522/index.html",
    sourceUrls: ["https://www.city.uruma.lg.jp/sportscamp/21522/index.html", "https://www.okinawastory.jp/stay/600011975"],
    warn:      false,
    lat:       26.41774,
    lng:       127.79255
  },
  {
    id:          42,
    code:        "47213-IS-0043",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "民宿レキオ",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川2-26-4",
    hours:     "チェックイン 16:00〜 / チェックアウト 〜10:00",
    closed:    "要確認",
    note:      "石川エリアの民宿",
    sourceUrl: "http://www.lequio7.sakura.ne.jp/",
    sourceUrls: ["http://www.lequio7.sakura.ne.jp/", "https://www.ekiten.jp/shop_2457906/", "https://travel.rakuten.co.jp/HOTEL/167138/review.html"],
    warn:      true,
    lat:       26.42586,
    lng:       127.82483
  },
  {
    id:          43,
    code:        "47213-IS-0044",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "民宿やすま",
    genre:     "宿泊",
    address:   "沖縄県うるま市石川曙2丁目3-1",
    hours:     "チェックイン 16:00〜 / チェックアウト 〜10:00",
    closed:    "要確認",
    note:      "石川エリアの民宿",
    sourceUrl: "https://uruma-ru.jp/stay/",
    sourceUrls: ["https://uruma-ru.jp/stay/", "https://www.ekiten.jp/shop_2457905/"],
    warn:      true,
    lat:       26.42059,
    lng:       127.82524
  },
  // ── 金融機関 ───────────────────────────────────────────────────
  {
    id:          44,
    code:        "47213-IS-0045",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "琉球銀行 石川支店",
    genre:     "金融",
    address:   "沖縄県うるま市石川2-23-6",
    hours:     "平日 9:00〜15:00",
    closed:    "土・日・祝日",
    note:      "ATMは時間外も利用可",
    sourceUrl: "https://www.ryugin.co.jp/tenpo/atm_search/shop-5030/",
    warn:      false,
    lat:       26.42626,
    lng:       127.82578
  },
  {
    id:          45,
    code:        "47213-IS-0046",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "沖縄銀行 石川支店",
    genre:     "金融",
    address:   "沖縄県うるま市石川2丁目24-1",
    hours:     "平日 9:00〜15:00",
    closed:    "土・日・祝日",
    note:      "ATMは時間外も利用可",
    sourceUrl: "https://gincode.com/branch_0188_315",
    sourceUrls: ["https://gincode.com/branch_0188_315", "https://www.okinawa-bank.co.jp/shop_atm/2014061100881/"],
    warn:      false,
    lat:       26.42580,
    lng:       127.82557
  },
  {
    id:          46,
    code:        "47213-IS-0047",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "石川郵便局",
    genre:     "金融",
    address:   "沖縄県うるま市石川東山本町1-1-2",
    hours:     "郵便 平日9:00〜17:00 / 貯金 平日9:00〜16:00",
    closed:    "土・日・祝日",
    note:      "ATMあり（土日も利用可）",
    sourceUrl: "https://map.japanpost.jp/p/search/dtl/300170031000/",
    sourceUrls: ["https://map.japanpost.jp/p/search/dtl/300170031000/", "https://map.yahoo.co.jp/v3/place/ls1CxYp0fJM"],
    warn:      false,
    lat:       26.43363,
    lng:       127.83207
  },
  // ── 教育施設 ───────────────────────────────────────────────────
  {
    id:          47,
    code:        "47213-IS-0048",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "うるま市立宮森小学校",
    genre:     "教育",
    address:   "沖縄県うるま市石川1丁目46-1",
    hours:     "平日 8:00〜17:00（登校日）",
    closed:    "土・日・祝日・長期休暇",
    note:      "",
    sourceUrl: "https://www.city.uruma.lg.jp/",
    sourceUrls: ["https://www.city.uruma.lg.jp/", "https://www.mapion.co.jp/phonebook/M11006/47213/ILSP0000077493_ipclm/"],
    warn:      false,
    lat:       26.43175,
    lng:       127.82759
  },
  {
    id:          48,
    code:        "47213-IS-0049",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "うるま市立石川中学校",
    genre:     "教育",
    address:   "沖縄県うるま市石川440番地1",
    hours:     "平日 8:00〜17:00（登校日）",
    closed:    "土・日・祝日・長期休暇",
    note:      "",
    sourceUrl: "https://j-ishikawa.edu.city.uruma.okinawa.jp/",
    sourceUrls: ["https://j-ishikawa.edu.city.uruma.okinawa.jp/", "https://www.city.uruma.lg.jp/3001002000/shisetsu/p000066.html"],
    warn:      false,
    lat:       26.42399,
    lng:       127.82429
  },
  {
    id:          49,
    code:        "47213-IS-0050",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "沖縄県立石川高等学校",
    genre:     "教育",
    address:   "沖縄県うるま市石川伊波861",
    hours:     "平日 8:00〜17:00（登校日）",
    closed:    "土・日・祝日・長期休暇",
    note:      "普通科",
    sourceUrl: "https://www.ishikawa-h.open.ed.jp/",
    sourceUrls: ["https://www.ishikawa-h.open.ed.jp/", "https://ja.wikipedia.org/wiki/沖縄県立石川高等学校"],
    warn:      false,
    lat:       26.41535,
    lng:       127.82052
  },
  // ── 観光スポット ───────────────────────────────────────────────
  {
    id:          50,
    code:        "47213-IS-0051",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "石川ビーチ（石川公園）",
    genre:     "観光",
    address:   "沖縄県うるま市石川曙",
    hours:     "年中無休（自由）",
    closed:    "なし",
    note:      "ウィンドサーフィンで有名な市民ビーチ。リーフ内は砂地で安全",
    sourceUrl: "https://www.okinawastory.jp/spot/600006184",
    sourceUrls: ["https://www.okinawastory.jp/spot/600006184", "https://www.city.uruma.lg.jp/1009007000/shisetsu/p000141.html"],
    warn:      false,
    lat:       26.42574,
    lng:       127.82849
  },
  {
    id:          51,
    code:        "47213-IS-0052",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "石川岳（市民の森公園）",
    genre:     "観光",
    address:   "沖縄県うるま市石川",
    hours:     "年中無休（自由）",
    closed:    "なし",
    note:      "標高204m。山頂展望台から太平洋と東シナ海を一望できる",
    sourceUrl: "https://www.city.uruma.lg.jp/miryoku/p000001.html",
    sourceUrls: ["https://www.city.uruma.lg.jp/miryoku/p000001.html", "https://uruma-portal.okinawa/archives/832"],
    warn:      false,
    lat:       26.44810,
    lng:       127.83208
  },

  // ── 美容・理容 ─────────────────────────────────────────────────
  // ※以下16件は2026-07-24にOSM抽出＋公式サイト/Yahoo!地図/エキテン等との
  // ウェブ複数照合（Agentツールによる並行検証）で追加
  {
    id:          52,
    code:        "47213-IS-0053",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "エステサロンDOUBLE（ダブル）",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川830-10",
    hours:     "10:00〜18:00",
    closed:    "日・月・祝日",
    note:      "エステサロン（脱毛・フェイシャル等）。国道329号(石川バイパス)沿い",
    note_en:   "Esthetic salon (hair removal, facial, etc.) along Route 329.",
    sourceUrl: "https://map.yahoo.co.jp/v3/place/-46DZn-74R6",
    sourceUrls: ["https://map.yahoo.co.jp/v3/place/-46DZn-74R6", "http://double-esthetic.com/", "https://double201551.ti-da.net/"],
    warn:      false,
    lat:       26.425014,
    lng:       127.820172,
    twitter: "", instagram: "", youtube: "", website: "http://double-esthetic.com/", detailText: "", photos: []
  },
  {
    id:          53,
    code:        "47213-IS-0054",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "IWASAKI沖縄石川店",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川1-16-1 マックスバリュ石川店1階",
    hours:     "10:00〜19:00",
    closed:    "年中無休",
    note:      "全国展開の美容室チェーン。マックスバリュ石川店1階",
    note_en:   "Nationwide hair salon chain IWASAKI, inside MaxValu Ishikawa store.",
    sourceUrl: "https://hkbn.co.jp/iwasaki/salon/list.php?pname=%E6%B2%96%E7%B8%84",
    sourceUrls: ["https://hkbn.co.jp/iwasaki/salon/list.php?pname=%E6%B2%96%E7%B8%84", "https://riyou.jp/shop/96183/"],
    warn:      false,
    lat:       26.430901,
    lng:       127.824645,
    twitter: "", instagram: "", youtube: "", website: "https://hkbn.co.jp/iwasaki/", detailText: "", photos: []
  },
  {
    id:          54,
    code:        "47213-IS-0055",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "IWASAKI沖縄赤崎店",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川赤崎2-1-1 サンエー赤崎店1階",
    hours:     "9:00〜18:00",
    closed:    "年中無休",
    note:      "全国展開の美容室チェーン。サンエー赤崎店1階",
    note_en:   "Nationwide hair salon chain IWASAKI, inside Sun-A Akasaki store.",
    sourceUrl: "https://hkbn.co.jp/iwasaki/salon/list.php?pname=%E6%B2%96%E7%B8%84",
    sourceUrls: ["https://hkbn.co.jp/iwasaki/salon/list.php?pname=%E6%B2%96%E7%B8%84", "https://riyou.jp/shop/96196/", "https://map.yahoo.co.jp/v3/place/Ud_QZ2rnhEg"],
    warn:      false,
    lat:       26.433345,
    lng:       127.834342,
    twitter: "", instagram: "", youtube: "", website: "https://hkbn.co.jp/iwasaki/", detailText: "", photos: []
  },
  {
    id:          55,
    code:        "47213-IS-0056",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "でいご理容館",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川1-52-36",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://www.navitime.co.jp/category/0402003/47213/",
    warn:      true,
    lat:       26.431154,
    lng:       127.829367,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          56,
    code:        "47213-IS-0057",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ヘアークラブイシトコ",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川1-27-25",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://www.navitime.co.jp/category/0402003/47213/",
    warn:      true,
    lat:       26.429498,
    lng:       127.827762,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          57,
    code:        "47213-IS-0058",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "クイン美容室",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川2丁目20-1",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://map.yahoo.co.jp/v3/place/Xu8xLHpHHrw",
    warn:      true,
    lat:       26.427057,
    lng:       127.825151,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          58,
    code:        "47213-IS-0059",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ごとう美容室",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川2丁目9-1",
    hours:     "要確認",
    closed:    "要確認",
    note:      "個人経営の老舗美容室。営業時間・定休日は要確認",
    note_en:   "Long-established, independently run hair salon. Please confirm hours and holidays before visiting.",
    sourceUrl: "https://map.yahoo.co.jp/v3/place/iocOXHLAbSY",
    warn:      true,
    lat:       26.428814,
    lng:       127.823964,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          59,
    code:        "47213-IS-0060",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ヘアーサロンジピー（ZiPPi）",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川白浜1丁目3-7",
    hours:     "10:00〜20:00",
    closed:    "月曜日",
    note:      "",
    note_en:   "",
    sourceUrl: "https://www.ekiten.jp/shop_2457063/",
    warn:      false,
    lat:       26.427888,
    lng:       127.827134,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          60,
    code:        "47213-IS-0061",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "カッティングハウスニューバニー3",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川白浜1丁目3-1",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://newbunny3.com/about/",
    sourceUrls: ["https://newbunny3.com/about/", "https://map.yahoo.co.jp/v3/place/5mC8cHKH_sc"],
    warn:      true,
    lat:       26.427557,
    lng:       127.827117,
    twitter: "", instagram: "", youtube: "", website: "https://newbunny3.com/", detailText: "", photos: []
  },
  {
    id:          61,
    code:        "47213-IS-0062",
    status:      "published",
    tel:         "",
    lastChecked: "2026-07-29",
    name:      "シルバー美容室",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川白浜1丁目2-7",
    hours:     "9:30〜18:00",
    closed:    "毎週火曜日・最終週の月曜日",
    note:      "美容・着付け専門店",
    note_en:   "Hair salon and kimono dressing specialist. Please confirm hours and holidays before visiting.",
    sourceUrl: "https://silver-hairmake.com/about/",
    sourceUrls: ["https://silver-hairmake.com/about/", "https://map.yahoo.co.jp/v3/place/03M-Nahf_U6"],
    warn:      false,
    lat:       26.427684,
    lng:       127.827421,
    twitter: "", instagram: "", youtube: "", website: "https://silver-hairmake.com/", detailText: "", photos: []
  },
  {
    id:          62,
    code:        "47213-IS-0063",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "ゆたか美容室",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川2丁目22-9",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://www.yelp.com/biz/%E3%82%86%E3%81%9F%E3%81%8B%E7%BE%8E%E5%AE%B9%E5%AE%A4-%E3%81%86%E3%82%8B%E3%81%BE%E5%B8%82",
    warn:      true,
    lat:       26.426258,
    lng:       127.825554,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          63,
    code:        "47213-IS-0064",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "スィートハンズ石川店",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川2丁目39-8",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://www.ekiten.jp/shop_2456829/",
    sourceUrls: ["https://www.ekiten.jp/shop_2456829/", "https://www.sweethands.net/salon/ishikawa/"],
    warn:      true,
    lat:       26.427584,
    lng:       127.821506,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          64,
    code:        "47213-IS-0065",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "夢咲美容室",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川東山1丁目12-11",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://www.ekiten.jp/shop_3616835/",
    warn:      true,
    lat:       26.435215,
    lng:       127.831579,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          65,
    code:        "47213-IS-0066",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "美容室さえら",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川東恩納44-1",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://www.ekiten.jp/shop_2457849/",
    warn:      true,
    lat:       26.409203,
    lng:       127.828656,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          66,
    code:        "47213-IS-0067",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "グランディール",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川東恩納721-2",
    hours:     "9:00〜18:00",
    closed:    "火曜日",
    note:      "",
    note_en:   "",
    sourceUrl: "https://map.yahoo.co.jp/v3/place/NSvKcDoNksY",
    sourceUrls: ["https://map.yahoo.co.jp/v3/place/NSvKcDoNksY", "https://www.ekiten.jp/shop_7003915/"],
    warn:      false,
    lat:       26.413455,
    lng:       127.823629,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          67,
    code:        "47213-IS-0068",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "カットハウスIN",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川伊波810",
    hours:     "要確認",
    closed:    "要確認",
    note:      "営業時間・定休日は要確認",
    note_en:   "Please confirm hours and holidays before visiting.",
    sourceUrl: "https://map.yahoo.co.jp/v3/place/gor1YPjRz3M",
    warn:      true,
    lat:       26.41725,
    lng:       127.81932,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  // ※以下1件はOSM・ウェブ検索いずれでも発見できず、2026-07-24にユーザーが
  // Googleマップの現地写真で発見。住所・電話番号はウェブ複数照合で確認済みだが、
  // 店名変更（旧「ヘアープロジェクトサヴァ」）はウェブ上で未確認のため要確認扱い
  {
    id:          68,
    code:        "47213-IS-0069",
    status:      "published",
    tel:         "",
    lastChecked: "",
    name:      "セントジェームス石川店",
    genre:     "美容・理容",
    address:   "沖縄県うるま市石川2丁目1-7",
    hours:     "要確認",
    closed:    "要確認",
    note:      "旧店名「ヘアープロジェクトサヴァ」。店名変更は現地看板で確認、詳細は要確認",
    note_en:   "Formerly known as \"Hair Project Sava\". Name change confirmed on-site; please confirm details before visiting.",
    sourceUrl: "https://www.ekiten.jp/g0202/a47213/",
    warn:      true,
    lat:       26.427074,
    lng:       127.826201,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },

  // ── 観光（追加分）─────────────────────────────────────────────
  // ※以下1件は2026-08-02に追加。「石川について」ページ作成中に発見。
  // 実在・住所・電話・開館時間はうるま市公式サイトと沖縄観光情報WEBサイト
  // 「おきなわ物語」（沖縄観光コンベンションビューロー）で一致を確認。
  // 座標はOSM(node/1068017752)を採用し、国土地理院の住所検索と31m以内で一致。
  {
    id:          69,
    code:        "47213-IS-0070",
    status:      "published",
    tel:         "098-965-3866",
    lastChecked: "2026-08-02",
    name:      "うるま市立石川歴史民俗資料館",
    genre:     "観光",
    address:   "沖縄県うるま市石川曙2丁目1-55",
    hours:     "9:00〜17:00（最終入館16:30）",
    closed:    "月曜（祝祭日と重なる場合は翌日）、祝祭日の翌日、年末年始（12月29日〜1月3日）",
    note:      "入館無料。石川図書館の2階。戦争・収容所関係資料、復元した規格住宅、宮森ジェット機墜落事故の関連資料などを展示。駐車場20台",
    note_en:   "Free admission. On the 2nd floor of Ishikawa Library. Exhibits cover the postwar civilian camp, a restored standard house, and the 1959 Miyamori jet crash.",
    sourceUrl: "https://www.city.uruma.lg.jp/bunka/1282.html",
    sourceUrls: ["https://www.city.uruma.lg.jp/bunka/1282.html", "https://www.okinawastory.jp/spot/20100300", "https://www.jalan.net/kankou/spt_guide000000168873/"],
    warn:      false,
    lat:       26.421856,
    lng:       127.825245,
    twitter: "", instagram: "", youtube: "", website: "https://www.city.uruma.lg.jp/bunka/1282.html", detailText: "", photos: []
  },

  // ── 観光・教育（追加分）───────────────────────────────────────
  // ※以下4件は2026-08-03に追加。「石川について」ページ作成時のarea-profile調査
  // （うるま市教育委員会リーフレット・市公式サイト）で見つかった候補をOSM抽出＋
  // ウェブ複数照合で検証。座標は国土地理院の住所検索とOSMを突合（詳細は各note参照）。
  // 同時に見つかった以下は住所・座標の確証が取れず今回は保留：
  // 伊波貝塚（国指定史跡、大字レベルの住所のみで特定不可）、
  // 沖縄諮詢会堂跡・石川部落事務所（市指定文化財、住所情報が見つからず/一部で
  // 資料館と同一住所という疑わしい情報のみ）、エナジックスタジアム石川
  // （住所表記がサイトごとに揺れ、国土地理院とOSMの座標が232m離れ不一致）。
  {
    id:          70,
    code:        "47213-IS-0071",
    status:      "published",
    tel:         "098-964-4888",
    lastChecked: "2026-08-03",
    name:      "CAVE OKINAWA",
    genre:     "観光",
    address:   "沖縄県うるま市石川嘉手苅479-1",
    hours:     "9:00〜17:30（最終入場17:00）。夏季延長期間は18:30まで（最終入場18:00）",
    closed:    "年中無休",
    note:      "全長200mの鍾乳洞。大人1,200円・子供600円・幼児無料。無料駐車場70台。石川ICから車で約5分",
    note_en:   "A 200m limestone cave. Adults ¥1,200, children ¥600, infants free. Free parking (70 spaces).",
    sourceUrl: "https://www.cave.okinawa/",
    sourceUrls: ["https://www.cave.okinawa/", "https://www.okinawastory.jp/spot/600010161"],
    warn:      false,
    lat:       26.422075,
    lng:       127.807503,
    twitter: "", instagram: "", youtube: "", website: "https://www.cave.okinawa/", detailText: "", photos: []
  },
  {
    id:          71,
    code:        "47213-IS-0072",
    status:      "published",
    tel:         "",
    lastChecked: "2026-08-03",
    name:      "伊波城跡",
    genre:     "観光",
    address:   "沖縄県うるま市石川伊波",
    hours:     "見学自由",
    closed:    "なし",
    note:      "県指定史跡。標高87mの伊波丘陵にあるグスク跡。座標はOSM登録のみで住所ベースの裏取りは大字レベルまで（要確認の範囲は数十m程度）",
    note_en:   "A prefecturally designated historic castle site atop the 87m Iha hill.",
    sourceUrl: "https://www.okinawastory.jp/spot/30000101",
    warn:      true,
    lat:       26.421474,
    lng:       127.817138,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  },
  {
    id:          72,
    code:        "47213-IS-0073",
    status:      "published",
    tel:         "098-923-7612",
    lastChecked: "2026-08-03",
    name:      "石川多目的ドーム",
    genre:     "観光",
    address:   "沖縄県うるま市石川2298-1",
    hours:     "見学自由（闘牛大会は年25回ほど開催、日程は公式サイト参照）",
    closed:    "なし",
    note:      "県内唯一の全天候型闘牛場。2007年完成。うるま市は全国で初めて「闘牛のまち」を宣言。座標は市公式サイト記載値とOSMが7m以内で一致",
    note_en:   "Okinawa's only all-weather bullfighting arena, completed in 2007.",
    sourceUrl: "https://www.city.uruma.lg.jp/1007003000/shisetsu/p000260.html",
    warn:      false,
    lat:       26.436185,
    lng:       127.825552,
    twitter: "", instagram: "", youtube: "", website: "https://www.city.uruma.lg.jp/1007003000/shisetsu/p000260.html", detailText: "", photos: []
  },
  {
    id:          73,
    code:        "47213-IS-0074",
    status:      "published",
    tel:         "098-964-2086",
    lastChecked: "2026-08-03",
    name:      "うるま市立城前小学校",
    genre:     "教育",
    address:   "沖縄県うるま市石川400",
    hours:     "平日 8:00〜17:00（登校日）",
    closed:    "土・日・祝日・長期休暇",
    note:      "戦後最初の学校「石川学園」の流れをくむ学校。校内に「戦後教育発祥之地」の碑がある",
    sourceUrl: "https://www.city.uruma.lg.jp/3001002000/shisetsu/p000050.html",
    sourceUrls: ["https://www.city.uruma.lg.jp/3001002000/shisetsu/p000050.html", "https://www.pref.okinawa.jp/edu/shien/gakko/sho/144.html"],
    warn:      false,
    lat:       26.424265,
    lng:       127.822790,
    twitter: "", instagram: "", youtube: "", website: "", detailText: "", photos: []
  }
];
